'use client'

import { useMemo, useState } from 'react'
import { money, type BusinessTarget, type Expense, type Order, type Product, type Worker } from '../../lib/itemku'
import { type ChannelRule, type DashboardPreferences, type Dispute, type PurchaseOrder, type Settlement } from '../../lib/v4'
import { actionCenter, profitProtection, reorderBatchPlanner, scenarioLab, shiftHandover, workingCapitalPlanner } from '../../lib/v44'

type V44Ctx={
  products:Product[];orders:Order[];expenses:Expense[];purchaseOrders:PurchaseOrder[];settlements:Settlement[];disputes:Dispute[];
  channelRules:ChannelRule[];workers:Worker[];targets:BusinessTarget[];dashboardPreferences:DashboardPreferences;setActive:(s:string)=>void
}
const pct=(n:number)=>`${Number.isFinite(n)?n.toFixed(1):'0.0'}%`
const num=(n:number)=>new Intl.NumberFormat('id-ID').format(Math.round(n))
function Card({title,subtitle,children,action}:{title:string;subtitle?:string;children:React.ReactNode;action?:React.ReactNode}){return <section className="rounded-2xl border bg-card p-4 shadow-sm md:p-5"><div className="mb-4 flex items-start justify-between gap-3"><div><h2 className="font-black tracking-tight">{title}</h2>{subtitle&&<p className="mt-1 text-xs text-muted-foreground">{subtitle}</p>}</div>{action}</div>{children}</section>}
function Metric({label,value,tone}:{label:string;value:string;tone?:'good'|'warn'|'bad'}){const cls=tone==='good'?'text-emerald-700 dark:text-emerald-300':tone==='warn'?'text-amber-700 dark:text-amber-300':tone==='bad'?'text-red-600 dark:text-red-300':'';return <div className="rounded-2xl border bg-card p-4"><p className="text-xs font-semibold text-muted-foreground">{label}</p><p className={`mt-1 text-xl font-black ${cls}`}>{value}</p></div>}
function Badge({children,tone='gray'}:{children:React.ReactNode;tone?:'green'|'red'|'amber'|'blue'|'gray'}){const cls={green:'bg-emerald-100 text-emerald-800 dark:bg-emerald-950 dark:text-emerald-200',red:'bg-red-100 text-red-700 dark:bg-red-950 dark:text-red-200',amber:'bg-amber-100 text-amber-800 dark:bg-amber-950 dark:text-amber-200',blue:'bg-blue-100 text-blue-800 dark:bg-blue-950 dark:text-blue-200',gray:'bg-muted text-muted-foreground'}[tone];return <span className={`inline-flex rounded-full px-2 py-1 text-[10px] font-black ${cls}`}>{children}</span>}
function Table({headers,children}:{headers:string[];children:React.ReactNode}){return <div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-xs"><thead><tr className="border-b text-muted-foreground">{headers.map(h=><th key={h} className="px-3 py-2 font-bold">{h}</th>)}</tr></thead><tbody>{children}</tbody></table></div>}
function Td({children,className=''}:{children:React.ReactNode;className?:string}){return <td className={`border-b px-3 py-3 align-top ${className}`}>{children}</td>}
function Empty({text}:{text:string}){return <div className="rounded-xl border border-dashed p-8 text-center text-sm text-muted-foreground">{text}</div>}

export function ActionCenterView(c:V44Ctx){
  const rows=useMemo(()=>actionCenter(c.products,c.orders,c.settlements,c.disputes,c.targets),[c.products,c.orders,c.settlements,c.disputes,c.targets])
  const p1=rows.filter(x=>x.priority==='P1').length,p2=rows.filter(x=>x.priority==='P2').length,impact=rows.reduce((s,x)=>s+x.impact,0)
  return <div className="space-y-5"><section className="grid gap-3 sm:grid-cols-3"><Metric label="Prioritas P1" value={String(p1)} tone={p1?'bad':'good'}/><Metric label="Prioritas P2" value={String(p2)} tone={p2?'warn':'good'}/><Metric label="Nilai yang perlu diperhatikan" value={money(impact)} tone={impact?'warn':'good'}/></section><Card title="Action Center V5.2" subtitle="Mengubah insight menjadi daftar tindakan Owner yang diurutkan berdasarkan urgensi dan dampak."><div className="grid gap-3 lg:grid-cols-2">{rows.map(x=><button key={x.id} onClick={()=>c.setActive(x.target)} className="rounded-xl border p-4 text-left transition hover:bg-muted/40"><div className="flex items-center justify-between gap-2"><strong className="text-sm">{x.title}</strong><div className="flex gap-1"><Badge tone={x.priority==='P1'?'red':x.priority==='P2'?'amber':'blue'}>{x.priority}</Badge><Badge>{x.category}</Badge></div></div><p className="mt-2 text-xs text-muted-foreground">{x.detail}</p>{x.impact>0&&<p className="mt-2 text-xs font-bold">Impact: {money(x.impact)}</p>}<p className="mt-3 text-[10px] font-black text-primary">Buka {x.target} →</p></button>)}</div>{!rows.length&&<Empty text="Tidak ada tindakan prioritas saat ini."/>}</Card></div>
}

export function WorkingCapitalView(c:V44Ctx){
  const x=useMemo(()=>workingCapitalPlanner(c.products,c.orders,c.expenses,c.purchaseOrders,c.settlements),[c.products,c.orders,c.expenses,c.purchaseOrders,c.settlements])
  return <div className="space-y-5"><section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Health Score" value={`${x.score}/100`} tone={x.score>=70?'good':x.score>=45?'warn':'bad'}/><Metric label="Modal di stok" value={money(x.stockCapital)} tone={x.stockCapital?'warn':undefined}/><Metric label="Komitmen PO" value={money(x.openPoCommitment)} tone={x.openPoCommitment?'warn':undefined}/><Metric label="Belum cair" value={money(x.unpaidSettlement)} tone={x.unpaidSettlement?'warn':'good'}/></section><div className="grid gap-5 xl:grid-cols-2"><Card title="Working Capital Planner" subtitle="Melihat tekanan modal dari stok, PO, pencairan, dan biaya 30 hari."><div className="grid gap-3 sm:grid-cols-2"><Metric label="Profit kotor 30h" value={money(x.grossProfit30)} tone={x.grossProfit30>=0?'good':'bad'}/><Metric label="Profit operasi 30h" value={money(x.netOperating30)} tone={x.netOperating30>=0?'good':'bad'}/><Metric label="Burn pengeluaran / hari" value={money(x.dailyExpenseBurn)} tone={x.dailyExpenseBurn?'warn':undefined}/><Metric label="Avg profit bersih / hari" value={money(x.avgDailyProfit)} tone={x.avgDailyProfit>=0?'good':'bad'}/></div></Card><Card title="Interpretasi"><div className="space-y-3 text-sm"><div className="flex items-center justify-between"><span>Tekanan likuiditas</span><Badge tone={x.liquidityPressure==='Rendah'?'green':x.liquidityPressure==='Sedang'?'amber':'red'}>{x.liquidityPressure}</Badge></div><div className="flex items-center justify-between"><span>Coverage stok keseluruhan</span><strong>{x.stockCoverageDays===null?'Belum cukup data':`${x.stockCoverageDays.toFixed(1)} hari`}</strong></div><p className="rounded-xl bg-muted p-3 text-xs text-muted-foreground">Score mempertimbangkan modal tertahan, PO yang belum selesai, payout belum cair, profit operasi, dan coverage stok. Gunakan sebagai indikator operasional, bukan saldo kas bank.</p></div></Card></div></div>
}

export function ScenarioLabView(c:V44Ctx){
  const [sales,setSales]=useState(0),[fee,setFee]=useState(0),[refund,setRefund]=useState(0),[expense,setExpense]=useState(0)
  const x=useMemo(()=>scenarioLab(c.orders,c.expenses,{salesChangePct:sales,feeDeltaPct:fee,refundChangePct:refund,expenseChangePct:expense}),[c.orders,c.expenses,sales,fee,refund,expense])
  return <div className="space-y-5"><Card title="Scenario Lab" subtitle="Uji dampak perubahan penjualan, fee, refund, dan pengeluaran berdasarkan baseline 30 hari terakhir."><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><NumInput label="Perubahan sales (%)" value={sales} onChange={setSales}/><NumInput label="Tambahan fee (%)" value={fee} onChange={setFee}/><NumInput label="Perubahan refund (poin %)" value={refund} onChange={setRefund}/><NumInput label="Perubahan expense (%)" value={expense} onChange={setExpense}/></div><button className="btn-secondary mt-4" onClick={()=>{setSales(0);setFee(0);setRefund(0);setExpense(0)}}>Reset Skenario</button></Card><section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-6"><Metric label="Baseline omzet" value={money(x.baselineRevenue)}/><Metric label="Scenario omzet" value={money(x.scenarioRevenue)}/><Metric label="Baseline profit" value={money(x.baselineProfit)} tone={x.baselineProfit>=0?'good':'bad'}/><Metric label="Scenario profit" value={money(x.scenarioProfit)} tone={x.scenarioProfit>=0?'good':'bad'}/><Metric label="Δ Profit" value={money(x.deltaProfit)} tone={x.deltaProfit>=0?'good':'bad'}/><Metric label="Margin scenario" value={pct(x.scenarioMargin)} tone={x.scenarioMargin>=10?'good':x.scenarioMargin>=0?'warn':'bad'}/></section><Card title="Catatan skenario"><div className="grid gap-2">{x.note.map((n,i)=><p key={i} className="rounded-xl border p-3 text-xs text-muted-foreground">• {n}</p>)}</div></Card></div>
}

export function ReorderPlannerView(c:V44Ctx){
  const rows=useMemo(()=>reorderBatchPlanner(c.products,c.orders),[c.products,c.orders]);const total=rows.reduce((s,x)=>s+x.totalCost,0),units=rows.reduce((s,x)=>s+x.totalQty,0)
  return <div className="space-y-5"><section className="grid gap-3 sm:grid-cols-3"><Metric label="Supplier perlu PO" value={String(rows.length)} tone={rows.length?'warn':'good'}/><Metric label="Unit disarankan" value={num(units)}/><Metric label="Estimasi modal" value={money(total)} tone={total?'warn':undefined}/></section><Card title="Reorder Batch Planner" subtitle="Mengelompokkan rekomendasi Smart Restock per supplier agar pembelian stok bisa dibuat sekaligus."><Table headers={['Supplier','Produk','Urgensi','Qty','Modal/unit','Total']}>{rows.flatMap(batch=>batch.items.map((x,i)=><tr key={`${batch.supplier}-${x.productId}`}><Td>{i===0?<><strong>{batch.supplier}</strong><small className="block text-muted-foreground">{batch.items.length} SKU</small></>:''}</Td><Td><strong>{x.productName}</strong><small className="block text-muted-foreground">{x.game}</small></Td><Td><Badge tone={x.urgency==='Kritis'?'red':x.urgency==='Segera'?'amber':'blue'}>{x.urgency}</Badge></Td><Td>{num(x.qty)}</Td><Td>{money(x.unitCost)}</Td><Td>{money(x.cost)}</Td></tr>))}</Table>{!rows.length&&<Empty text="Belum ada batch restock yang disarankan."/>}</Card><div className="flex justify-end"><button onClick={()=>c.setActive('Purchase Order')} className="btn-primary">Buka Purchase Order</button></div></div>
}

export function ProfitProtectionView(c:V44Ctx){
  const channels=[...new Set(['Itemku','WhatsApp','Direct',...c.channelRules.filter(x=>x.active).map(x=>x.name)])];const [channel,setChannel]=useState(channels[0]||'Itemku');const [buffer,setBuffer]=useState(5)
  const rows=useMemo(()=>profitProtection(c.products,c.channelRules,channel,buffer),[c.products,c.channelRules,channel,buffer]);const unsafe=rows.filter(x=>x.status!=='Aman')
  return <div className="space-y-5"><Card title="Profit Protection" subtitle="Hitung harga minimum aman per channel sebelum fee atau biaya membuat margin bocor."><div className="grid gap-3 sm:grid-cols-2"><label className="grid gap-1 text-xs font-bold">Channel<select className="input h-10" value={channel} onChange={(e:any)=>setChannel(e.target.value)}>{channels.map(x=><option key={x}>{x}</option>)}</select></label><NumInput label="Buffer minimum (%)" value={buffer} onChange={v=>setBuffer(Math.max(0,v))}/></div></Card><section className="grid gap-3 sm:grid-cols-3"><Metric label="Produk aman" value={String(rows.filter(x=>x.status==='Aman').length)} tone="good"/><Metric label="Margin tipis" value={String(rows.filter(x=>x.status==='Tipis').length)} tone={rows.some(x=>x.status==='Tipis')?'warn':'good'}/><Metric label="Berpotensi rugi" value={String(rows.filter(x=>x.status==='Rugi').length)} tone={rows.some(x=>x.status==='Rugi')?'bad':'good'}/></section><Card title="Harga terlindungi" subtitle="Target Price mempertimbangkan fee channel, BEP, buffer minimum, dan target margin produk."><Table headers={['Produk','Harga sekarang','Min aman','Target','Margin sekarang','Margin target','Status']}>{rows.map(x=><tr key={x.productId}><Td><strong>{x.productName}</strong><small className="block text-muted-foreground">{x.game} · {x.channel}</small></Td><Td>{money(x.currentPrice)}</Td><Td>{money(x.minimumPrice)}</Td><Td><strong>{money(x.targetPrice)}</strong></Td><Td>{pct(x.currentMargin)}</Td><Td>{pct(x.protectedMargin)}</Td><Td><Badge tone={x.status==='Aman'?'green':x.status==='Tipis'?'amber':'red'}>{x.status}</Badge></Td></tr>)}</Table>{!unsafe.length&&<p className="mt-3 text-xs text-emerald-700">Semua produk aktif berada di atas buffer margin yang dipilih.</p>}</Card></div>
}

export function ShiftHandoverView(c:V44Ctx){
  const x=useMemo(()=>shiftHandover(c.workers,c.orders,c.disputes,c.dashboardPreferences?.slaMinutes||10),[c.workers,c.orders,c.disputes,c.dashboardPreferences])
  return <div className="space-y-5"><section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><Metric label="Order aktif" value={String(x.pending)} tone={x.pending?'warn':'good'}/><Metric label="Menunggu" value={String(x.waiting)} tone={x.waiting?'warn':'good'}/><Metric label="Lewat SLA" value={String(x.overSla)} tone={x.overSla?'bad':'good'}/><Metric label="Belum assign" value={String(x.unassigned)} tone={x.unassigned?'warn':'good'}/><Metric label="Dispute terbuka" value={String(x.openDisputes)} tone={x.openDisputes?'warn':'good'}/></section><div className="grid gap-5 xl:grid-cols-[1.2fr_.8fr]"><Card title="Shift Handover" subtitle="Ringkasan beban Worker dan order yang perlu diteruskan saat pergantian shift."><Table headers={['Worker','Aktif','Menunggu','Order selesai hari ini','Order tertua','Game']}>{x.workers.map(w=><tr key={w.name}><Td><strong>{w.name}</strong></Td><Td>{w.activeOrders}</Td><Td>{w.waitingOrders}</Td><Td>{w.completedToday}</Td><Td>{w.oldestMinutes?`${Math.floor(w.oldestMinutes)} menit`:'-'}</Td><Td>{w.games.length?w.games.join(', '):'Semua'}</Td></tr>)}</Table>{!x.workers.length&&<Empty text="Belum ada Worker aktif."/>}</Card><Card title="Catatan handover"><div className="space-y-2">{x.notes.map((n,i)=><p key={i} className="rounded-xl border p-3 text-xs text-muted-foreground">• {n}</p>)}</div><div className="mt-4 grid gap-2 sm:grid-cols-2 xl:grid-cols-1"><button className="btn-secondary" onClick={()=>c.setActive('Worker Queue')}>Buka Worker Queue</button><button className="btn-secondary" onClick={()=>c.setActive('Order Kanban')}>Buka Order Kanban</button></div></Card></div></div>
}

function NumInput({label,value,onChange}:{label:string;value:number;onChange:(n:number)=>void}){return <label className="grid gap-1 text-xs font-bold">{label}<input className="input h-10" type="number" value={value} onChange={(e:any)=>onChange(Number(e.target.value)||0)}/></label>}
