'use client'
import { useEffect, useMemo, useState } from 'react'
import { appendAudit, exportBackup, restoreBackup } from '../../lib/itemku'
import { exportV4Backup, loadSyncQueue, restoreV4Backup } from '../../lib/v4'
import { ageLabel, bytesLabel, clearClientErrors, inspectBackupText, listRecoverySnapshots, loadClientErrors, saveRecoverySnapshot, deleteRecoverySnapshot, sha256Text, type BackupInspection, type ClientErrorEntry, type RecoverySnapshot } from '../../lib/v51'
import { exportV52Backup, restoreV52Backup } from '../../lib/v52'

type Ctx={products:any[];orders:any[];workers:any[];audit:any[];ownerCloud:boolean;online:boolean;syncState:string;realtimeStatus:string;setActive:(s:string)=>void;flash:(s:string)=>void}

type Health={ok?:boolean;app?:string;version?:string;cloudConfigured?:boolean;time?:string}
const download=(name:string,text:string,type='application/json')=>{const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();window.setTimeout(()=>URL.revokeObjectURL(url),1000)}
const currentBundle=()=>{const base=JSON.parse(exportBackup()),v4=JSON.parse(exportV4Backup()),v52=JSON.parse(exportV52Backup());return JSON.stringify({...base,version:5.2,release:'5.2.0-automation',exportedAt:new Date().toISOString(),v4,v52},null,2)}

export function ObservabilityCenterView(c:Ctx){
  const [health,setHealth]=useState<Health|null>(null),[latency,setLatency]=useState<number|null>(null),[storage,setStorage]=useState<{usage:number;quota:number}|null>(null),[errors,setErrors]=useState<ClientErrorEntry[]>([]),[busy,setBusy]=useState(false)
  const refreshErrors=()=>setErrors(loadClientErrors())
  const check=async()=>{setBusy(true);const start=performance.now();try{const r=await fetch('/api/health',{cache:'no-store'});const body=await r.json();setHealth(body);setLatency(Math.round(performance.now()-start))}catch{setHealth({ok:false});setLatency(null)}finally{setBusy(false)};try{const est=await navigator.storage?.estimate?.();if(est)setStorage({usage:est.usage||0,quota:est.quota||0})}catch{}}
  useEffect(()=>{void check();refreshErrors();const onErr=()=>refreshErrors();window.addEventListener('itemku:client-error',onErr);return()=>window.removeEventListener('itemku:client-error',onErr)},[])
  const pending=typeof window==='undefined'?[]:loadSyncQueue();const sw=typeof navigator!=='undefined'&&'serviceWorker'in navigator;const controlled=typeof navigator!=='undefined'&&Boolean(navigator.serviceWorker?.controller)
  const usagePct=storage?.quota?storage.usage/storage.quota*100:0
  return <div className="space-y-5">
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-6">
      <Metric label="Server" value={health?.ok?'Online':'Tidak terhubung'} state={health?.ok?'good':'bad'}/><Metric label="Latency" value={latency==null?'-':`${latency} ms`} state={latency!=null&&latency<800?'good':latency!=null?'warn':'bad'}/><Metric label="Cloud" value={c.ownerCloud?'Aktif':'Lokal'} state={c.ownerCloud?'good':'warn'}/><Metric label="Realtime" value={c.realtimeStatus||'-'} state={/aktif/i.test(c.realtimeStatus)?'good':'warn'}/><Metric label="Pending Sync" value={String(pending.length)} state={pending.length?'warn':'good'}/><Metric label="Client Error" value={String(errors.length)} state={errors.length?'warn':'good'}/>
    </section>
    <Card title="Observability Center" subtitle="Satu tempat untuk mengecek kesehatan browser, server, PWA, cloud, dan antrean sinkronisasi.">
      <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-4"><Mini label="Versi server" value={health?.version||'-'}/><Mini label="Supabase server" value={health?.cloudConfigured?'Configured':'Belum configured'}/><Mini label="Service Worker" value={sw?(controlled?'Aktif':'Tersedia, belum control'):'Tidak tersedia'}/><Mini label="Koneksi browser" value={c.online?'Online':'Offline'}/></div>
      <div className="mt-4 rounded-xl border p-4"><div className="flex items-center justify-between gap-3"><div><strong className="text-sm">Storage browser</strong><p className="text-xs text-muted-foreground">{storage?`${bytesLabel(storage.usage)} dari ${bytesLabel(storage.quota)} (${usagePct.toFixed(2)}%)`:'Informasi quota tidak tersedia.'}</p></div><button className="btn-secondary" disabled={busy} onClick={()=>void check()}>{busy?'Mengecek...':'Tes ulang'}</button></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-primary" style={{width:`${Math.min(100,usagePct)}%`}}/></div></div>
    </Card>
    <Card title="Antrean Sync" subtitle="Mutation yang belum berhasil dikirim ke cloud.">{pending.length?<div className="space-y-2">{pending.slice(0,12).map((x:any)=><div key={x.id} className="rounded-xl border p-3 text-xs"><div className="flex justify-between gap-3"><strong>{x.entity}</strong><span>{ageLabel(x.createdAt)}</span></div><p className="mt-1 text-muted-foreground">{x.upserts?.length||0} upsert · {x.deletedIds?.length||0} delete · percobaan {x.tries||0}</p>{x.lastError&&<p className="mt-1 text-red-600">{x.lastError}</p>}</div>)}</div>:<Empty text="Tidak ada pending sync."/>}</Card>
    <Card title="Client Error Journal" subtitle="Menyimpan maksimal 50 error browser terbaru secara lokal; tidak mengirim detail ke pihak luar."><div className="mb-3 flex justify-end"><button className="btn-secondary" onClick={()=>{clearClientErrors();refreshErrors();c.flash('Client error journal dibersihkan')}}>Bersihkan</button></div>{errors.length?<div className="space-y-2">{errors.slice(0,15).map(e=><div key={e.id} className="rounded-xl border p-3"><div className="flex flex-wrap justify-between gap-2"><strong className="text-xs">{e.message}</strong><span className="text-[10px] text-muted-foreground">{new Date(e.createdAt).toLocaleString('id-ID')}</span></div><p className="mt-1 break-all text-[10px] text-muted-foreground">{e.source}</p></div>)}</div>:<Empty text="Belum ada client error yang tercatat."/>}</Card>
  </div>
}

export function RecoveryCenterView(c:Ctx){
  const [snapshots,setSnapshots]=useState<RecoverySnapshot[]>([]),[preview,setPreview]=useState<{text:string;name:string;info:BackupInspection;checksum:string}|null>(null),[busy,setBusy]=useState(false)
  const load=async()=>setSnapshots(await listRecoverySnapshots())
  useEffect(()=>{void load()},[])
  const checkpoint=async()=>{setBusy(true);try{const payload=currentBundle();const snap=await saveRecoverySnapshot(`Checkpoint V5.2 ${new Date().toLocaleString('id-ID')}`,payload);localStorage.setItem('itemkuLastCheckpointAt',snap.createdAt);appendAudit('Recovery checkpoint','V5.2 local IndexedDB');await load();c.flash('Checkpoint lokal dibuat')}catch(e:any){c.flash(e.message||'Checkpoint gagal')}finally{setBusy(false)}}
  const inspect=async(text:string,name:string)=>{const info=inspectBackupText(text);const checksum=await sha256Text(text);setPreview({text,name,info,checksum})}
  const applyRestore=async()=>{if(!preview)return;setBusy(true);try{await saveRecoverySnapshot('Auto checkpoint sebelum restore',currentBundle());restoreBackup(preview.text);const d=JSON.parse(preview.text);try{if(d.v4)restoreV4Backup(JSON.stringify(d.v4));else restoreV4Backup(preview.text)}catch{}try{if(d.v52)restoreV52Backup(JSON.stringify(d.v52))}catch{}appendAudit('Restore aman',`${preview.name} · SHA256 ${preview.checksum.slice(0,12)}`);localStorage.setItem('itemkuLastRestoreAt',new Date().toISOString());window.location.reload()}catch(e:any){c.flash(e.message||'Restore gagal');setBusy(false)}}
  return <div className="space-y-5">
    <section className="grid gap-3 md:grid-cols-3"><button disabled={busy} onClick={()=>void checkpoint()} className="action-card"><strong>Buat Checkpoint Lokal</strong><span>Disimpan ke IndexedDB dan diputar otomatis maksimal 5 snapshot.</span></button><label className="action-card cursor-pointer"><strong>Preview File Backup</strong><span>Backup tidak diterapkan sebelum lolos pemeriksaan.</span><input type="file" accept=".json,application/json" className="hidden" onChange={(e:any)=>{const f=e.target.files?.[0];if(f)void f.text().then((t:string)=>inspect(t,f.name))}}/></label><button className="action-card" onClick={()=>{const payload=currentBundle();download(`itemku-v5.2-backup-${new Date().toISOString().replace(/[:.]/g,'-')}.json`,payload);localStorage.setItem('itemkuLastBackupAt',new Date().toISOString());window.dispatchEvent(new Event('itemku:backup'));c.flash('Backup V5.2 diunduh')}}><strong>Download Backup V5.2</strong><span>Backup eksternal tetap menjadi perlindungan utama.</span></button></section>
    {preview&&<Card title={`Restore Preview · ${preview.name}`} subtitle="Periksa isi sebelum menekan restore."><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><Metric label="Status" value={preview.info.critical.length?'Diblokir':'Siap direstore'} state={preview.info.critical.length?'bad':'good'}/><Mini label="Versi" value={preview.info.release}/><Mini label="Produk" value={String(preview.info.counts.products)}/><Mini label="Order" value={String(preview.info.counts.orders)}/><Mini label="Worker" value={String(preview.info.counts.workers)}/></div><div className="mt-4 grid gap-3 lg:grid-cols-2"><div className="rounded-xl border p-3"><strong className="text-xs">Integrity SHA-256</strong><p className="mt-1 break-all font-mono text-[10px] text-muted-foreground">{preview.checksum}</p></div><div className="rounded-xl border p-3"><strong className="text-xs">Timestamp</strong><p className="mt-1 text-xs text-muted-foreground">{preview.info.exportedAt?new Date(preview.info.exportedAt).toLocaleString('id-ID'):'Tidak tersedia'}</p></div></div>{preview.info.critical.length>0&&<IssueBox title="Isu kritis" rows={preview.info.critical} bad/>}{preview.info.warnings.length>0&&<IssueBox title="Peringatan" rows={preview.info.warnings}/>}<div className="mt-4 flex flex-wrap gap-2"><button disabled={busy||preview.info.critical.length>0} className="btn-primary" onClick={()=>void applyRestore()}>{busy?'Memproses...':'Buat checkpoint lalu Restore'}</button><button className="btn-secondary" onClick={()=>setPreview(null)}>Batal</button></div></Card>}
    <Card title="Recovery Vault" subtitle="Checkpoint lokal untuk rollback cepat. Tetap simpan backup eksternal karena vault berada di browser yang sama.">{snapshots.length?<div className="space-y-2">{snapshots.map(s=><div key={s.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border p-3"><div><strong className="text-xs">{s.name}</strong><p className="mt-1 text-[10px] text-muted-foreground">{new Date(s.createdAt).toLocaleString('id-ID')} · {bytesLabel(s.bytes)} · {s.checksum.slice(0,16)}…</p></div><div className="flex gap-2"><button className="btn-secondary" onClick={()=>void inspect(s.payload,`${s.name}.json`)}>Preview</button><button className="btn-secondary" onClick={()=>download(`recovery-${s.id}.json`,s.payload)}>Download</button><button className="btn-secondary" onClick={()=>void deleteRecoverySnapshot(s.id).then(load)}>Hapus</button></div></div>)}</div>:<Empty text="Belum ada checkpoint lokal."/>}</Card>
  </div>
}

export function AuditEvidenceView(c:Ctx){
  const [query,setQuery]=useState(''),[from,setFrom]=useState(''),[to,setTo]=useState(''),[checksum,setChecksum]=useState('')
  const rows=useMemo(()=>c.audit.filter((a:any)=>{const t=new Date(a.createdAt).getTime();if(from&&t<new Date(`${from}T00:00:00`).getTime())return false;if(to&&t>new Date(`${to}T23:59:59.999`).getTime())return false;const q=query.trim().toLowerCase();return !q||`${a.action} ${a.detail||''} ${a.actor||''}`.toLowerCase().includes(q)}),[c.audit,query,from,to])
  const exportJson=async()=>{const payload=JSON.stringify({release:'5.2.0-automation',exportedAt:new Date().toISOString(),filters:{query,from,to},audit:rows},null,2);const hash=await sha256Text(payload);setChecksum(hash);download(`audit-evidence-${Date.now()}.json`,payload);download(`audit-evidence-${Date.now()}.sha256.txt`,hash,'text/plain');c.flash('Audit evidence + checksum diunduh')}
  const exportCsv=()=>{const esc=(v:any)=>`"${String(v??'').replace(/"/g,'""')}"`;const csv=['createdAt,actor,action,detail',...rows.map((a:any)=>[a.createdAt,a.actor,a.action,a.detail].map(esc).join(','))].join('\n');download(`audit-evidence-${Date.now()}.csv`,csv,'text/csv;charset=utf-8');c.flash('Audit CSV diunduh')}
  return <div className="space-y-5"><Card title="Audit & Evidence" subtitle="Filter riwayat perubahan lalu ekspor bukti audit beserta checksum SHA-256."><div className="grid gap-3 md:grid-cols-4"><Field label="Cari" value={query} onChange={setQuery} placeholder="refund, harga, worker..."/><Field label="Dari" value={from} onChange={setFrom} type="date"/><Field label="Sampai" value={to} onChange={setTo} type="date"/><div className="flex items-end gap-2"><button className="btn-primary" onClick={()=>void exportJson()}>JSON + SHA</button><button className="btn-secondary" onClick={exportCsv}>CSV</button></div></div>{checksum&&<p className="mt-3 break-all rounded-xl border bg-muted/30 p-3 font-mono text-[10px]">SHA-256 terakhir: {checksum}</p>}</Card><Card title={`${rows.length} Audit Event`}><div className="space-y-2">{rows.slice(0,100).map((a:any)=><div key={a.id} className="grid gap-1 rounded-xl border p-3 md:grid-cols-[170px_140px_1fr]"><span className="text-[10px] text-muted-foreground">{new Date(a.createdAt).toLocaleString('id-ID')}</span><strong className="text-xs">{a.actor||'Owner'}</strong><div><strong className="text-xs">{a.action}</strong>{a.detail&&<p className="mt-1 text-[10px] text-muted-foreground">{a.detail}</p>}</div></div>)}{!rows.length&&<Empty text="Tidak ada event sesuai filter."/>}</div></Card></div>
}

function Card({title,subtitle,children}:{title:string;subtitle?:string;children:React.ReactNode}){return <section className="rounded-2xl border bg-card p-5 shadow-sm"><h2 className="text-base font-black">{title}</h2>{subtitle&&<p className="mt-1 text-xs text-muted-foreground">{subtitle}</p>}<div className="mt-4">{children}</div></section>}
function Metric({label,value,state}:{label:string;value:string;state?:'good'|'warn'|'bad'}){const cls=state==='good'?'text-emerald-700':state==='warn'?'text-amber-700':state==='bad'?'text-red-600':'';return <div className="rounded-xl border bg-card p-4"><span className="text-xs text-muted-foreground">{label}</span><strong className={`mt-1 block text-lg ${cls}`}>{value}</strong></div>}
function Mini({label,value}:{label:string;value:string}){return <div className="rounded-xl border p-3"><span className="text-[10px] font-black uppercase tracking-wider text-muted-foreground">{label}</span><p className="mt-1 text-sm font-black">{value}</p></div>}
function Field({label,value,onChange,placeholder,type='text'}:{label:string;value:string;onChange:(v:string)=>void;placeholder?:string;type?:string}){return <label className="grid gap-1.5 text-xs font-semibold">{label}<input type={type} value={value} onChange={(e:any)=>onChange(e.target.value)} placeholder={placeholder} className="input h-10"/></label>}
function IssueBox({title,rows,bad=false}:{title:string;rows:string[];bad?:boolean}){return <div className={`mt-3 rounded-xl border p-3 ${bad?'border-red-200 bg-red-50 text-red-700 dark:border-red-900 dark:bg-red-950/20':'border-amber-200 bg-amber-50 text-amber-800 dark:border-amber-900 dark:bg-amber-950/20'}`}><strong className="text-xs">{title}</strong><ul className="mt-2 list-disc space-y-1 pl-4 text-xs">{rows.map(x=><li key={x}>{x}</li>)}</ul></div>}
function Empty({text}:{text:string}){return <p className="rounded-xl border border-dashed p-7 text-center text-sm text-muted-foreground">{text}</p>}
