'use client'

import { useMemo, useState } from 'react'
import { appendAudit, id, makeSnapshot, money, nextLocalInvoice, updateProductWithHistory, type Expense, type Order, type PriceHistory, type Product } from '../../lib/itemku'
import { cloudAction } from '../../lib/cloud'
import { feeForChannel, type ChannelRule, type Dispute, type InventoryLedger, type PurchaseOrder, type Settlement } from '../../lib/v4'
import { calendarSummary, customerIntelligence, dailyOperations, dataQuality, duplicateProduct, priceAdvisor, repairSafeData, salesTrendRadar } from '../../lib/v42'

export type V42Ctx={
  products:Product[];orders:Order[];expenses:Expense[];history:PriceHistory[];channelRules:ChannelRule[];purchaseOrders:PurchaseOrder[];settlements:Settlement[];disputes:Dispute[];inventoryLedger:InventoryLedger[];
  ownerCloud:boolean;saveProductsV:(x:Product[])=>void;saveOrdersV:(x:Order[])=>void;saveHistoryV:(x:PriceHistory[])=>void;hydrateCloud:()=>Promise<void>|void;flash:(s:string)=>void;setActive:(s:string)=>void
}
const pct=(n:number)=>`${Number.isFinite(n)?n.toFixed(1):'0.0'}%`
const fmt=(v?:string)=>v?new Date(v).toLocaleString('id-ID'):'-'

export function QuickOrderView(c:V42Ctx){
  const active=c.products.filter(p=>p.active&&p.stock>0)
  const [query,setQuery]=useState('');const [productId,setProductId]=useState(active[0]?.id||'');const [buyer,setBuyer]=useState('');const [server,setServer]=useState('');const [qty,setQty]=useState(1);const [channel,setChannel]=useState('Itemku');const [note,setNote]=useState('');const [busy,setBusy]=useState(false)
  const rows=active.filter(p=>`${p.game} ${p.name} ${p.sku}`.toLowerCase().includes(query.toLowerCase())).slice(0,12);const product=c.products.find(p=>p.id===productId);const rule=product?feeForChannel(c.channelRules,channel,product):null;const snapshot=product?makeSnapshot({...product,fee:rule?.feePercent??product.fee,fixed:rule?.fixedFee??product.fixed},Math.max(1,qty)):null
  const create=async()=>{if(!product)return c.flash('Pilih produk');if(!buyer.trim())return c.flash('Username/User ID wajib diisi');if(product.stock<qty)return c.flash(`Stok tidak cukup. Tersedia ${product.stock}`);setBusy(true);try{if(c.ownerCloud){await cloudAction('createOrder',{productId:product.id,buyerIdentifier:buyer.trim(),serverId:server.trim(),channel,qty,note:note.trim()});await c.hydrateCloud()}else{const now=new Date().toISOString();const o:Order={id:id('order'),invoiceNo:nextLocalInvoice(c.orders),productId:product.id,productName:product.name,game:product.game,supplierSnapshot:product.supplier,buyerIdentifier:buyer.trim(),serverId:server.trim(),channel,qty,note:note.trim(),createdAt:now,status:'Baru',snapshot:snapshot!};c.saveProductsV(c.products.map(p=>p.id===product.id?{...p,stock:p.stock-qty,updatedAt:now}:p));c.saveOrdersV([...c.orders,o]);appendAudit('Quick Order dibuat',`${o.invoiceNo} · ${o.productName}`)}setBuyer('');setServer('');setNote('');setQty(1);c.flash('Quick Order berhasil dibuat')}catch(e:any){c.flash(e.message||'Order gagal')}finally{setBusy(false)}}
  return <div className="grid gap-5 xl:grid-cols-[1.1fr_.9fr]"><Card title="Quick Order V5.2" subtitle="Alur singkat untuk order WhatsApp/direct: pilih produk → pembeli → buat order."><div className="grid gap-3 sm:grid-cols-2"><Field label="Cari produk" value={query} onChange={setQuery}/><Select label="Channel" value={channel} onChange={setChannel} options={[...new Set(['Itemku','WhatsApp','Direct',...c.channelRules.filter(x=>x.active).map(x=>x.name)])]}/></div><div className="mt-4 grid gap-2 sm:grid-cols-2">{rows.map(p=><button key={p.id} onClick={()=>setProductId(p.id)} className={`rounded-xl border p-3 text-left ${productId===p.id?'border-primary bg-primary/5':'hover:bg-muted/40'}`}><strong className="text-sm">{p.name}</strong><small className="block text-muted-foreground">{p.game} · {p.sku||'-'} · stok {p.stock}</small></button>)}</div>{!rows.length&&<Empty text="Produk tidak ditemukan atau stok habis."/>}<div className="mt-5 grid gap-3 sm:grid-cols-2"><Field label="Username / User ID" value={buyer} onChange={setBuyer}/><Field label="Server / UID tambahan" value={server} onChange={setServer}/><Num label="Qty" value={qty} onChange={v=>setQty(Math.max(1,v))}/><Field label="Catatan" value={note} onChange={setNote}/></div><button disabled={busy||!product} onClick={()=>void create()} className="btn-primary mt-5 w-full">{busy?'Memproses...':'Buat Order Sekarang'}</button></Card><Card title="Preview transaksi">{product&&snapshot?<div className="grid gap-3"><Mini label="Produk" value={`${product.game} · ${product.name}`}/><Mini label="Stok setelah order" value={String(Math.max(0,product.stock-qty))}/><Metric label="Omzet" value={money(snapshot.revenue)}/><Metric label="Profit estimasi" value={money(snapshot.profit)} tone={snapshot.profit>=0?'good':'bad'}/><Mini label="Fee channel" value={`${rule?.feePercent??product.fee}% + ${money(rule?.fixedFee??product.fixed)}`}/></div>:<Empty text="Pilih produk untuk melihat preview."/>}</Card></div>
}

export function PriceAdvisorView(c:V42Ctx){
  const [productId,setProductId]=useState(c.products.find(p=>p.active)?.id||'');const [channel,setChannel]=useState('Itemku');const product=c.products.find(p=>p.id===productId);const rows=product?priceAdvisor(product,c.channelRules,channel):[]
  const apply=(price:number)=>{if(!product)return;const next={...product,price,updatedAt:new Date().toISOString()};c.saveHistoryV(updateProductWithHistory(product,next,c.history));c.saveProductsV(c.products.map(p=>p.id===product.id?next:p));appendAudit('Price Advisor',`${product.name}: ${money(product.price)} → ${money(price)}`);c.flash('Harga master diperbarui')}
  return <div className="space-y-5"><Card title="Auto Price Advisor" subtitle="Menghitung harga aman berdasarkan modal, fee channel, biaya tetap, dan target margin. Harga dibulatkan ke nominal jual yang lebih praktis."><div className="grid gap-3 sm:grid-cols-2"><label className="grid gap-1.5 text-xs font-semibold">Produk<select className="input h-10" value={productId} onChange={e=>setProductId(e.target.value)}>{c.products.filter(p=>p.active).map(p=><option key={p.id} value={p.id}>{p.game} · {p.name}</option>)}</select></label><Select label="Channel" value={channel} onChange={setChannel} options={[...new Set(['Itemku','WhatsApp','Direct',...c.channelRules.filter(x=>x.active).map(x=>x.name)])]}/></div></Card>{product&&<section className="grid gap-3 sm:grid-cols-4"><Metric label="Modal" value={money(product.modal)}/><Metric label="Harga sekarang" value={money(product.price)}/><Metric label="Target produk" value={pct(product.target)}/><Metric label="Stok" value={String(product.stock)}/></section>}<Card title="Saran harga"><Table headers={['Target margin','Harga matematis','Harga saran','Profit/unit','ROI','Aksi']}>{rows.map(x=><tr key={x.margin}><Td><strong>{x.margin}%</strong></Td><Td>{money(x.raw)}</Td><Td><strong>{money(x.rounded)}</strong></Td><Td className={x.profit>=0?'text-emerald-700':'text-red-600'}>{money(x.profit)}</Td><Td>{pct(x.roi)}</Td><Td><button className="tiny-btn" onClick={()=>apply(x.rounded)}>Pakai harga</button></Td></tr>)}</Table>{!product&&<Empty text="Belum ada produk."/>}</Card></div>
}

export function ProductTemplateView(c:V42Ctx){
  const [q,setQ]=useState('');const rows=c.products.filter(p=>`${p.game} ${p.name} ${p.sku}`.toLowerCase().includes(q.toLowerCase()))
  const duplicate=(p:Product)=>{const copy=duplicateProduct(c.products,p);c.saveProductsV([...c.products,copy]);appendAudit('Duplikasi produk',`${p.name} → ${copy.name}`);localStorage.setItem('itemkuEditProduct',copy.id);c.flash('Template produk dibuat dengan stok 0');c.setActive('Tambah Produk')}
  return <Card title="Product Templates & Duplicate" subtitle="Duplikasi struktur produk tanpa menyalin stok. Cocok untuk banyak varian dalam game yang sama." action={<input className="input h-9 w-56" placeholder="Cari produk" value={q} onChange={e=>setQ(e.target.value)}/>}><Table headers={['Produk','SKU','Supplier','Harga','Stok','Aksi']}>{rows.map(p=><tr key={p.id}><Td><strong>{p.name}</strong><small className="block text-muted-foreground">{p.game} · {p.category}</small></Td><Td>{p.sku||'-'}</Td><Td>{p.supplier||'-'}</Td><Td>{money(p.price)}</Td><Td>{p.stock}</Td><Td><button className="tiny-btn" onClick={()=>duplicate(p)}>Duplicate → Edit</button></Td></tr>)}</Table></Card>
}

export function CustomerIntelligenceView(c:V42Ctx){
  const [q,setQ]=useState('');const rows=useMemo(()=>customerIntelligence(c.orders,c.disputes),[c.orders,c.disputes]).filter(x=>x.buyer.toLowerCase().includes(q.toLowerCase()))
  return <div className="space-y-5"><section className="grid gap-3 sm:grid-cols-4"><Metric label="VIP" value={String(rows.filter(x=>x.loyalty==='VIP').length)} tone="good"/><Metric label="Repeat/Loyal" value={String(rows.filter(x=>x.loyalty==='Loyal').length)}/><Metric label="Risk tinggi" value={String(rows.filter(x=>x.risk==='Tinggi').length)} tone="bad"/><Metric label="Total pelanggan" value={String(rows.length)}/></section><Card title="Customer Loyalty & Risk" subtitle="Skor loyalty menggunakan frekuensi, nilai belanja, recency, dan refund. Risk menggunakan refund ratio + dispute aktif." action={<input className="input h-9 w-56" placeholder="Cari pelanggan" value={q} onChange={e=>setQ(e.target.value)}/>}><Table headers={['Pelanggan','Order','Belanja','AOV','Loyalty','Risk','Refund','Dispute','Terakhir']}>{rows.map(x=><tr key={x.buyer.toLowerCase()}><Td><strong>{x.buyer}</strong></Td><Td>{x.orders}</Td><Td>{money(x.spend)}</Td><Td>{money(x.aov)}</Td><Td><Badge tone={x.loyalty==='VIP'?'green':x.loyalty==='Loyal'?'blue':'gray'}>{x.loyalty} · {x.loyaltyScore}</Badge></Td><Td><Badge tone={x.risk==='Tinggi'?'red':x.risk==='Sedang'?'amber':'green'}>{x.risk} · {x.riskScore}</Badge></Td><Td>{pct(x.refundRate*100)}</Td><Td>{x.openDisputes}</Td><Td>{fmt(x.lastAt)}</Td></tr>)}</Table></Card></div>
}

export function SalesTrendRadarView(c:V42Ctx){
  const rows=useMemo(()=>salesTrendRadar(c.products,c.orders),[c.products,c.orders]);const [filter,setFilter]=useState('Semua');const shown=filter==='Semua'?rows:rows.filter(x=>x.label===filter)
  return <div className="space-y-5"><section className="grid gap-3 sm:grid-cols-4"><Metric label="Trend naik" value={String(rows.filter(x=>x.label==='Naik').length)} tone="good"/><Metric label="Produk baru bergerak" value={String(rows.filter(x=>x.label==='Baru').length)}/><Metric label="Stabil" value={String(rows.filter(x=>x.label==='Stabil').length)}/><Metric label="Trend turun" value={String(rows.filter(x=>x.label==='Turun').length)} tone="warn"/></section><Card title="Sales Trend Radar" subtitle="Membandingkan unit terjual 7 hari terakhir dengan 7 hari sebelumnya." action={<select className="input h-9" value={filter} onChange={e=>setFilter(e.target.value)}><option>Semua</option><option>Naik</option><option>Baru</option><option>Stabil</option><option>Turun</option></select>}><Table headers={['Produk','7 hari','7 hari sebelumnya','Perubahan','Profit 7 hari','Sinyal']}>{shown.map(x=><tr key={x.productId}><Td><strong>{x.productName}</strong><small className="block text-muted-foreground">{x.game}</small></Td><Td>{x.last7}</Td><Td>{x.prev7}</Td><Td>{x.growth===null?'Baru':pct(x.growth)}</Td><Td className={x.profit7>=0?'text-emerald-700':'text-red-600'}>{money(x.profit7)}</Td><Td><Badge tone={x.label==='Naik'?'green':x.label==='Turun'?'red':x.label==='Baru'?'blue':'gray'}>{x.label}</Badge></Td></tr>)}</Table></Card></div>
}

export function DailyOperationsView(c:V42Ctx){
  const actions=useMemo(()=>dailyOperations(c.products,c.orders,c.purchaseOrders,c.settlements,c.disputes,c.channelRules),[c.products,c.orders,c.purchaseOrders,c.settlements,c.disputes,c.channelRules])
  const today=new Date();today.setHours(0,0,0,0);const done=c.orders.filter(o=>o.status==='Selesai'&&new Date(o.completedAt||o.createdAt)>=today);const revenue=done.reduce((s,o)=>s+o.snapshot.revenue,0);const profit=done.reduce((s,o)=>s+o.snapshot.profit,0)
  return <div className="space-y-5"><section className="grid gap-3 sm:grid-cols-4"><Metric label="Selesai hari ini" value={String(done.length)}/><Metric label="Omzet hari ini" value={money(revenue)}/><Metric label="Profit hari ini" value={money(profit)} tone={profit>=0?'good':'bad'}/><Metric label="Action items" value={String(actions.filter(x=>x.priority<3).length)} tone={actions.some(x=>x.priority===1)?'warn':undefined}/></section><Card title="Daily Operations" subtitle="Checklist otomatis untuk hal yang paling perlu ditangani Owner hari ini."><div className="space-y-3">{actions.map(x=><button key={x.id} onClick={()=>c.setActive(x.target)} className="flex w-full items-start justify-between gap-4 rounded-xl border p-4 text-left hover:bg-muted/30"><div><strong className="text-sm">{x.title}</strong><p className="mt-1 text-xs text-muted-foreground">{x.detail}</p></div><Badge tone={x.priority===1?'red':x.priority===2?'amber':'green'}>{x.priority===1?'Prioritas':x.priority===2?'Perlu cek':'Aman'}</Badge></button>)}</div></Card></div>
}

export function DataQualityView(c:V42Ctx){
  const issues=useMemo(()=>dataQuality(c.products,c.orders,c.inventoryLedger),[c.products,c.orders,c.inventoryLedger]);const fixable=issues.filter(x=>x.fixable)
  const repair=()=>{if(!fixable.length)return c.flash('Tidak ada masalah aman yang perlu diperbaiki');if(!confirm(`Perbaiki ${fixable.length} masalah aman? SKU kosong/duplikat dan invoice kosong/duplikat akan dinormalisasi.`))return;const next=repairSafeData(c.products,c.orders);c.saveProductsV(next.products);c.saveOrdersV(next.orders);appendAudit('Data Quality auto-fix',`${fixable.length} masalah diperbaiki`);c.flash('Perbaikan data aman selesai')}
  return <div className="space-y-5"><section className="grid gap-3 sm:grid-cols-4"><Metric label="Critical" value={String(issues.filter(x=>x.level==='danger').length)} tone={issues.some(x=>x.level==='danger')?'bad':'good'}/><Metric label="Warning" value={String(issues.filter(x=>x.level==='warn').length)} tone={issues.some(x=>x.level==='warn')?'warn':'good'}/><Metric label="Info" value={String(issues.filter(x=>x.level==='info').length)}/><Metric label="Auto-fix aman" value={String(fixable.length)}/></section><Card title="Data Quality Center" subtitle="Mendeteksi duplicate SKU/invoice, SKU kosong, order historis tanpa master produk, dan mismatch stok-vs-ledger." action={<button className="btn-primary" onClick={repair} disabled={!fixable.length}>Perbaiki Aman ({fixable.length})</button>}><div className="space-y-2">{issues.map(x=><div key={x.id} className={`rounded-xl border p-3 ${x.level==='danger'?'border-red-200 bg-red-50 dark:bg-red-950/20':x.level==='warn'?'border-amber-200 bg-amber-50 dark:bg-amber-950/20':'bg-muted/20'}`}><div className="flex items-start justify-between gap-3"><div><strong className="text-sm">{x.title}</strong><p className="mt-1 text-xs text-muted-foreground">{x.detail}</p></div>{x.fixable&&<Badge tone="blue">Auto-fix</Badge>}</div></div>)}{!issues.length&&<Empty text="Data sehat. Tidak ada anomali yang terdeteksi."/>}</div></Card></div>
}

export function BusinessCalendarView(c:V42Ctx){
  const [cursor,setCursor]=useState(()=>{const d=new Date();return new Date(d.getFullYear(),d.getMonth(),1)});const year=cursor.getFullYear(),month=cursor.getMonth();const firstDay=new Date(year,month,1).getDay();const days=new Date(year,month+1,0).getDate();const cells:(Date|null)[]=[...Array(firstDay).fill(null),...Array.from({length:days},(_,i)=>new Date(year,month,i+1))];while(cells.length%7)cells.push(null)
  const monthTotals=cells.filter(Boolean).map(d=>calendarSummary(d!,c.orders,c.expenses,c.purchaseOrders,c.settlements,c.disputes)).reduce((a,x)=>({orders:a.orders+x.orders,revenue:a.revenue+x.revenue,profit:a.profit+x.profit,expenses:a.expenses+x.expenses,po:a.po+x.po,settlements:a.settlements+x.settlements,disputes:a.disputes+x.disputes}),{orders:0,revenue:0,profit:0,expenses:0,po:0,settlements:0,disputes:0})
  return <div className="space-y-5"><section className="grid gap-3 sm:grid-cols-4"><Metric label="Order selesai" value={String(monthTotals.orders)}/><Metric label="Omzet bulan" value={money(monthTotals.revenue)}/><Metric label="Profit kotor" value={money(monthTotals.profit)} tone={monthTotals.profit>=0?'good':'bad'}/><Metric label="Expense" value={money(monthTotals.expenses)} tone="warn"/></section><Card title="Business Calendar" subtitle="Order, expense, PO, payout, dan dispute dalam satu kalender." action={<div className="flex items-center gap-2"><button className="tiny-btn" onClick={()=>setCursor(new Date(year,month-1,1))}>←</button><strong className="min-w-36 text-center text-sm">{cursor.toLocaleDateString('id-ID',{month:'long',year:'numeric'})}</strong><button className="tiny-btn" onClick={()=>setCursor(new Date(year,month+1,1))}>→</button></div>}><div className="grid grid-cols-7 gap-1 text-center text-[10px] font-bold text-muted-foreground">{['Min','Sen','Sel','Rab','Kam','Jum','Sab'].map(x=><div key={x} className="p-2">{x}</div>)}</div><div className="grid grid-cols-7 gap-1">{cells.map((d,i)=>{if(!d)return <div key={`empty-${i}`} className="min-h-24 rounded-lg bg-muted/10"/>;const s=calendarSummary(d,c.orders,c.expenses,c.purchaseOrders,c.settlements,c.disputes);const busy=s.orders||s.expenses||s.po||s.settlements||s.disputes;return <div key={d.toISOString()} className={`min-h-24 rounded-lg border p-2 ${busy?'bg-card':'bg-muted/10'}`}><strong className="text-xs">{d.getDate()}</strong>{s.orders>0&&<small className="mt-2 block text-emerald-700">✓ {s.orders} order</small>}{s.profit!==0&&<small className="block text-emerald-700">{money(s.profit)}</small>}{s.expenses>0&&<small className="block text-red-600">− {money(s.expenses)}</small>}{s.po>0&&<small className="block text-blue-600">PO {s.po}</small>}{s.settlements>0&&<small className="block text-purple-600">Payout {s.settlements}</small>}{s.disputes>0&&<small className="block text-amber-700">Dispute {s.disputes}</small>}</div>})}</div></Card></div>
}

function Card({title,subtitle,children,action}:{title:string;subtitle?:string;children:React.ReactNode;action?:React.ReactNode}){return <section className="rounded-2xl border bg-card p-5 shadow-sm"><div className="mb-4 flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-base font-bold">{title}</h2>{subtitle&&<p className="mt-1 max-w-3xl text-xs leading-relaxed text-muted-foreground">{subtitle}</p>}</div>{action}</div>{children}</section>}
function Metric({label,value,tone}:{label:string;value:string;tone?:'good'|'bad'|'warn'}){const cls=tone==='good'?'text-emerald-700':tone==='bad'?'text-red-600':tone==='warn'?'text-amber-700':'';return <div className="rounded-xl border bg-card p-4"><span className="block text-xs text-muted-foreground">{label}</span><strong className={`mt-1 block text-xl ${cls}`}>{value}</strong></div>}
function Field({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <label className="grid gap-1.5 text-xs font-semibold">{label}<input value={value} onChange={e=>onChange(e.target.value)} className="input h-10"/></label>}
function Num({label,value,onChange}:{label:string;value:number;onChange:(v:number)=>void}){return <label className="grid gap-1.5 text-xs font-semibold">{label}<input type="number" min="1" value={value} onChange={e=>onChange(Math.max(1,Number(e.target.value)||1))} className="input h-10"/></label>}
function Select({label,value,onChange,options}:{label:string;value:string;onChange:(v:string)=>void;options:string[]}){return <label className="grid gap-1.5 text-xs font-semibold">{label}<select value={value} onChange={e=>onChange(e.target.value)} className="input h-10">{options.map(x=><option key={x}>{x}</option>)}</select></label>}
function Table({headers,children}:{headers:string[];children:React.ReactNode}){return <div className="overflow-x-auto"><table className="w-full min-w-[820px] border-collapse text-left text-xs"><thead><tr>{headers.map(h=><th key={h} className="border-b px-3 py-2.5 font-semibold text-muted-foreground">{h}</th>)}</tr></thead><tbody>{children}</tbody></table></div>}
function Td({children,className=''}:{children:React.ReactNode;className?:string}){return <td className={`border-b px-3 py-3 align-top ${className}`}>{children}</td>}
function Badge({children,tone='gray'}:{children:React.ReactNode;tone?:string}){const cls=tone==='green'?'bg-emerald-100 text-emerald-800 dark:bg-emerald-950 dark:text-emerald-200':tone==='red'?'bg-red-100 text-red-700 dark:bg-red-950 dark:text-red-200':tone==='amber'?'bg-amber-100 text-amber-800 dark:bg-amber-950 dark:text-amber-200':tone==='blue'?'bg-blue-100 text-blue-700 dark:bg-blue-950 dark:text-blue-200':'bg-muted text-muted-foreground';return <span className={`inline-flex rounded-full px-2 py-1 text-[10px] font-bold ${cls}`}>{children}</span>}
function Mini({label,value}:{label:string;value:string}){return <div><span className="block text-[10px] font-bold uppercase tracking-wider text-muted-foreground">{label}</span><p className="mt-1 text-sm font-semibold">{value}</p></div>}
function Empty({text}:{text:string}){return <p className="rounded-xl border border-dashed p-6 text-center text-xs text-muted-foreground">{text}</p>}
