'use client'

import { useEffect, useMemo, useState } from 'react'
import type { Order, Product } from '../../lib/itemku'
import type { Supplier } from '../../lib/v4'

type Props={open:boolean;setOpen:(v:boolean)=>void;products:Product[];orders:Order[];suppliers:Supplier[];setActive:(s:string)=>void}

export function CommandPalette({open,setOpen,products,orders,suppliers,setActive}:Props){
  const [q,setQ]=useState('')
  useEffect(()=>{const key=(e:KeyboardEvent)=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();setOpen(!open)}if(e.key==='Escape')setOpen(false)};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[open,setOpen])
  useEffect(()=>{if(!open)setQ('')},[open])
  const actions=[['Buat order','Quick Order'],['Action Center','Action Center'],['Working Capital','Working Capital'],['Scenario Lab','Scenario Lab'],['Reorder Planner','Reorder Planner'],['Profit Protection','Profit Protection'],['Shift Handover','Shift Handover'],['Tambah produk','Tambah Produk'],['Restock produk','Restock'],['Supplier Center','Supplier Center'],['Purchase Order','Purchase Order'],['Inventory Ledger','Inventory Ledger'],['Settlement','Settlement & Rekonsiliasi'],['Automation','Automation & Forecast'],['Automation Runner','Automation Runner'],['Approval Center','Approval Center'],['Scheduled Reports','Scheduled Reports'],['Maintenance Center','Maintenance Center'],['Observability','Observability Center'],['Recovery','Recovery Center'],['Audit Evidence','Audit & Evidence'],['Health Center','Health & Import']]
  const results=useMemo(()=>{const s=q.trim().toLowerCase();if(!s)return actions.slice(0,8).map(([label,target])=>({type:'Aksi',label,target,sub:''}));const rows:any[]=[];for(const [label,target] of actions)if(label.toLowerCase().includes(s))rows.push({type:'Aksi',label,target,sub:''});for(const p of products)if(`${p.name} ${p.game} ${p.sku} ${p.supplier}`.toLowerCase().includes(s))rows.push({type:'Produk',label:p.name,target:'Daftar Produk',sub:`${p.game} · ${p.sku||'-'} · stok ${p.stock}`});for(const o of orders.slice(0,500))if(`${o.invoiceNo} ${o.buyerIdentifier} ${o.productName}`.toLowerCase().includes(s))rows.push({type:'Order',label:o.invoiceNo,target:'Order Center',sub:`${o.buyerIdentifier} · ${o.productName}`});for(const x of suppliers)if(`${x.name} ${x.contact}`.toLowerCase().includes(s))rows.push({type:'Supplier',label:x.name,target:'Supplier Center',sub:x.contact||''});return rows.slice(0,20)},[q,products,orders,suppliers])
  if(!open)return null
  return <div className="fixed inset-0 z-[100] bg-black/40 p-4 backdrop-blur-sm" onMouseDown={()=>setOpen(false)}><div className="mx-auto mt-[10vh] max-w-2xl overflow-hidden rounded-2xl border bg-card shadow-2xl" onMouseDown={e=>e.stopPropagation()}><div className="border-b p-3"><input autoFocus value={q} onChange={e=>setQ(e.target.value)} placeholder="Cari invoice, pembeli, produk, SKU, supplier, atau aksi..." className="input h-12 w-full border-0 text-base focus:ring-0"/></div><div className="max-h-[60vh] overflow-y-auto p-2">{results.map((r,i)=><button key={`${r.type}-${r.label}-${i}`} onClick={()=>{setActive(r.target);setOpen(false)}} className="flex w-full items-center justify-between gap-3 rounded-xl p-3 text-left hover:bg-muted"><div><strong className="text-sm">{r.label}</strong>{r.sub&&<p className="text-xs text-muted-foreground">{r.sub}</p>}</div><span className="rounded-full bg-muted px-2 py-1 text-[10px] font-bold text-muted-foreground">{r.type}</span></button>)}{!results.length&&<p className="p-8 text-center text-sm text-muted-foreground">Tidak ditemukan.</p>}</div><div className="border-t px-4 py-2 text-[10px] text-muted-foreground">Ctrl/⌘ + K untuk buka · Esc untuk tutup</div></div></div>
}
