'use client'
import { useEffect, useMemo, useState } from 'react'
import { appendAudit, money, type Expense, type Order, type Product } from '../../lib/itemku'
import { type AutomationRule, type NotificationItem } from '../../lib/v4'
import { applyApproval, decideApproval, exportV52Backup, generateScheduledReport, loadApprovals, loadAutomationRuns, loadReportSchedules, loadScheduledReports, maintenanceSnapshot, makeReportSchedule, runAutomation, runDueReportSchedules, safeMaintenance, saveApprovals, saveReportSchedules, saveScheduledReports, type ApprovalRequest, type ReportFrequency, type ReportSchedule, type ScheduledReport } from '../../lib/v52'

export type V52Ctx={products:Product[];orders:Order[];expenses:Expense[];automationRules:AutomationRule[];notifications:NotificationItem[];saveNotificationsV:(x:NotificationItem[])=>void;saveProductsV:(x:Product[])=>void;setActive:(s:string)=>void;flash:(s:string)=>void}
const fmt=(iso?:string)=>iso?new Date(iso).toLocaleString('id-ID'):'-'
const download=(name:string,text:string,type='application/json')=>{const u=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),800)}
function Card({title,subtitle,children,action}:{title:string;subtitle?:string;children:React.ReactNode;action?:React.ReactNode}){return <section className="rounded-2xl border bg-card p-5 shadow-sm"><div className="mb-4 flex flex-wrap items-start justify-between gap-3"><div><h2 className="font-black">{title}</h2>{subtitle&&<p className="mt-1 text-xs text-muted-foreground">{subtitle}</p>}</div>{action}</div>{children}</section>}
function Metric({label,value,tone}:{label:string;value:string;tone?:'good'|'warn'|'bad'}){const c=tone==='good'?'text-emerald-700':tone==='warn'?'text-amber-700':tone==='bad'?'text-red-600':'';return <div className="rounded-xl border bg-card p-4"><p className="text-xs text-muted-foreground">{label}</p><strong className={`mt-1 block text-xl ${c}`}>{value}</strong></div>}
function Badge({children,tone='gray'}:{children:React.ReactNode;tone?:'green'|'amber'|'red'|'blue'|'gray'}){const c={green:'bg-emerald-100 text-emerald-800',amber:'bg-amber-100 text-amber-800',red:'bg-red-100 text-red-700',blue:'bg-blue-100 text-blue-700',gray:'bg-muted text-muted-foreground'}[tone];return <span className={`rounded-full px-2 py-1 text-[10px] font-black ${c}`}>{children}</span>}
function Empty({text}:{text:string}){return <p className="rounded-xl border border-dashed p-8 text-center text-sm text-muted-foreground">{text}</p>}

export function AutomationRunnerView(c:V52Ctx){
  const [approvals,setApprovals]=useState<ApprovalRequest[]>([]),[runs,setRuns]=useState(loadAutomationRuns())
  useEffect(()=>setApprovals(loadApprovals()),[])
  const run=()=>{const x=runAutomation({products:c.products,orders:c.orders,rules:c.automationRules,notifications:c.notifications,approvals});c.saveNotificationsV(x.notifications);setApprovals(x.approvals);setRuns(loadAutomationRuns());appendAudit('Automation Runner V5.2',`${x.log.notificationsAdded} notifikasi · ${x.log.approvalsAdded} approval`);c.flash('Automation check selesai')}
  const pending=approvals.filter(x=>x.status==='Pending').length
  return <div className="space-y-5"><section className="grid gap-3 sm:grid-cols-3"><Metric label="Rule aktif" value={String(c.automationRules.filter(x=>x.enabled).length)}/><Metric label="Approval pending" value={String(pending)} tone={pending?'warn':'good'}/><Metric label="Run tercatat" value={String(runs.length)}/></section><Card title="Automation Runner" subtitle="Menjalankan rule operasional sekarang. Aksi yang mengubah harga/diskon tidak diterapkan otomatis—selalu masuk Approval Center dulu." action={<button onClick={run} className="btn-primary">▶ Jalankan sekarang</button>}><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-5">{c.automationRules.map(r=><div key={r.id} className="rounded-xl border p-3"><div className="flex items-center justify-between gap-2"><strong className="text-xs">{r.label}</strong><Badge tone={r.enabled?'green':'gray'}>{r.enabled?'Aktif':'Off'}</Badge></div><p className="mt-2 text-xs text-muted-foreground">Threshold: {r.threshold}</p></div>)}</div></Card><Card title="Riwayat Automation" action={<button className="btn-secondary" onClick={()=>c.setActive('Approval Center')}>Buka Approval Center</button>}>{runs.length?<div className="space-y-2">{runs.slice(0,12).map(x=><div key={x.id} className="rounded-xl border p-3 text-xs"><div className="flex justify-between gap-3"><strong>{fmt(x.createdAt)}</strong><span>{x.rulesChecked} rule</span></div><p className="mt-1 text-muted-foreground">+{x.notificationsAdded} notifikasi · +{x.approvalsAdded} approval · {x.note}</p></div>)}</div>:<Empty text="Belum ada Automation Runner yang dijalankan."/>}</Card></div>
}

export function ApprovalCenterView(c:V52Ctx){
  const [rows,setRows]=useState<ApprovalRequest[]>([]);useEffect(()=>setRows(loadApprovals()),[])
  const decide=(x:ApprovalRequest,status:'Disetujui'|'Ditolak')=>{const next=decideApproval(rows,x.id,status);setRows(next);appendAudit(`Approval ${status}`,`${x.title} · ${money(x.suggestedValue)}`);c.flash(`Approval ${status.toLowerCase()}`)}
  const apply=(x:ApprovalRequest)=>{try{const r=applyApproval(rows,c.products,x.id);c.saveProductsV(r.products);setRows(r.approvals);appendAudit('Approval diterapkan',`${x.title} · ${money(x.suggestedValue)}`);c.flash('Perubahan diterapkan')}catch(e:any){c.flash(e.message||'Gagal menerapkan approval')}}
  const pending=rows.filter(x=>x.status==='Pending'),approved=rows.filter(x=>x.status==='Disetujui')
  return <div className="space-y-5"><section className="grid gap-3 sm:grid-cols-3"><Metric label="Menunggu keputusan" value={String(pending.length)} tone={pending.length?'warn':'good'}/><Metric label="Siap diterapkan" value={String(approved.length)} tone={approved.length?'warn':'good'}/><Metric label="Total histori" value={String(rows.length)}/></section><Card title="Approval Center" subtitle="Lapisan persetujuan untuk perubahan sensitif hasil automation. Tidak ada perubahan produk sebelum Owner menekan Setujui dan Terapkan."><div className="space-y-3">{rows.slice(0,50).map(x=><div key={x.id} className="rounded-xl border p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><strong className="text-sm">{x.title}</strong><p className="mt-1 text-xs text-muted-foreground">{x.detail}</p><p className="mt-2 text-xs">{money(x.currentValue)} → <strong>{money(x.suggestedValue)}</strong></p></div><div className="flex gap-1"><Badge tone={x.risk==='Tinggi'?'red':x.risk==='Sedang'?'amber':'green'}>{x.risk}</Badge><Badge tone={x.status==='Pending'?'amber':x.status==='Disetujui'?'blue':x.status==='Diterapkan'?'green':'gray'}>{x.status}</Badge></div></div><div className="mt-3 flex flex-wrap gap-2">{x.status==='Pending'&&<><button className="btn-primary" onClick={()=>decide(x,'Disetujui')}>Setujui</button><button className="btn-secondary" onClick={()=>decide(x,'Ditolak')}>Tolak</button></>}{x.status==='Disetujui'&&<button className="btn-primary" onClick={()=>apply(x)}>Terapkan perubahan</button>}</div></div>)}{!rows.length&&<Empty text="Belum ada approval. Jalankan Automation Runner untuk membuat rekomendasi."/>}</div></Card></div>
}

export function ScheduledReportsView(c:V52Ctx){
  const [schedules,setSchedules]=useState<ReportSchedule[]>([]),[reports,setReports]=useState<ScheduledReport[]>([]),[name,setName]=useState('Laporan Mingguan'),[frequency,setFrequency]=useState<ReportFrequency>('Mingguan')
  const refresh=()=>{setSchedules(loadReportSchedules());setReports(loadScheduledReports())}
  useEffect(()=>{const x=runDueReportSchedules(loadReportSchedules(),c.orders,c.expenses);setSchedules(x.schedules);setReports(x.reports);if(x.generated)c.flash(`${x.generated} laporan terjadwal dibuat saat dashboard dibuka`)},[])
  const add=()=>{const next=[makeReportSchedule(name,frequency),...schedules];saveReportSchedules(next);setSchedules(next);c.flash('Jadwal laporan dibuat')}
  const runNow=(s:ReportSchedule)=>{const report=generateScheduledReport(s,c.orders,c.expenses);const next=[report,...loadScheduledReports()].slice(0,100);saveScheduledReports(next);setReports(next);const ss=schedules.map(x=>x.id===s.id?{...x,lastRunAt:new Date().toISOString()}:x);saveReportSchedules(ss);setSchedules(ss);c.flash('Laporan dibuat')}
  const toggle=(s:ReportSchedule)=>{const next=schedules.map(x=>x.id===s.id?{...x,enabled:!x.enabled}:x);saveReportSchedules(next);setSchedules(next)}
  const exportReport=(r:ScheduledReport)=>download(`itemku-${r.scheduleName.replace(/\s+/g,'-').toLowerCase()}-${r.createdAt.slice(0,10)}.json`,JSON.stringify(r,null,2))
  return <div className="space-y-5"><Card title="Scheduled Reports" subtitle="Jadwal diproses ketika Owner membuka dashboard/PWA. Browser yang benar-benar tertutup tidak dapat menjalankan laporan lokal di background."><div className="grid gap-3 sm:grid-cols-[1fr_180px_auto]"><input className="input h-10" value={name} onChange={(e:any)=>setName(e.target.value)} placeholder="Nama laporan"/><select className="input h-10" value={frequency} onChange={(e:any)=>setFrequency(e.target.value as ReportFrequency)}><option>Harian</option><option>Mingguan</option><option>Bulanan</option></select><button onClick={add} className="btn-primary">+ Jadwal</button></div></Card><div className="grid gap-5 xl:grid-cols-2"><Card title="Jadwal aktif"><div className="space-y-3">{schedules.map(s=><div key={s.id} className="rounded-xl border p-3"><div className="flex items-start justify-between gap-3"><div><strong className="text-sm">{s.name}</strong><p className="text-xs text-muted-foreground">{s.frequency} · berikutnya {fmt(s.nextRunAt)}</p></div><button onClick={()=>toggle(s)}><Badge tone={s.enabled?'green':'gray'}>{s.enabled?'Aktif':'Off'}</Badge></button></div><div className="mt-3 flex gap-2"><button className="btn-secondary" onClick={()=>runNow(s)}>Generate sekarang</button></div></div>)}{!schedules.length&&<Empty text="Belum ada jadwal laporan."/>}</div></Card><Card title="Laporan terbaru"><div className="space-y-3">{reports.slice(0,12).map(r=><div key={r.id} className="rounded-xl border p-3"><div className="flex items-start justify-between gap-3"><div><strong className="text-sm">{r.scheduleName}</strong><p className="text-xs text-muted-foreground">{fmt(r.createdAt)} · {r.orderCount} order · Top: {r.topProduct}</p></div><button className="tiny-btn" onClick={()=>exportReport(r)}>Export</button></div><div className="mt-2 grid grid-cols-2 gap-2 text-xs"><span>Omzet <strong>{money(r.revenue)}</strong></span><span>Profit bersih <strong className={r.netProfit>=0?'text-emerald-700':'text-red-600'}>{money(r.netProfit)}</strong></span></div></div>)}{!reports.length&&<Empty text="Belum ada laporan yang dihasilkan."/>}</div></Card></div></div>
}

export function MaintenanceCenterView(c:V52Ctx){
  const [tick,setTick]=useState(0);const x=useMemo(()=>maintenanceSnapshot(c.notifications),[c.notifications,tick])
  const clean=()=>{const result=safeMaintenance(c.notifications);c.saveNotificationsV(result.notifications);setTick(v=>v+1);appendAudit('Safe Maintenance V5.2',`${result.removedNotifications} notifikasi lama dibersihkan`);c.flash('Safe maintenance selesai')}
  const exportState=()=>download(`itemku-v5.2-maintenance-${new Date().toISOString().slice(0,10)}.json`,JSON.stringify({at:new Date().toISOString(),snapshot:x,v52:JSON.parse(exportV52Backup())},null,2))
  return <div className="space-y-5"><section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label="LocalStorage" value={`${(x.localStorageBytes/1024).toFixed(1)} KB`}/><Metric label="Approval pending" value={String(x.pendingApprovals)} tone={x.pendingApprovals?'warn':'good'}/><Metric label="Notifikasi lama" value={String(x.oldReadNotifications)} tone={x.oldReadNotifications?'warn':'good'}/><Metric label="Report history" value={String(x.scheduledReports)}/></section><Card title="Maintenance Center" subtitle="Pembersihan aman hanya menyentuh log/riwayat UI lama. Order, produk, ledger, payout, PO, dan data bisnis tidak dihapus."><div className="grid gap-3 md:grid-cols-2"><button onClick={clean} className="action-card"><strong>Safe Cleanup</strong><span>Hapus notifikasi yang sudah dibaca &gt;30 hari, batasi log automation/report, dan arsipkan approval lama.</span></button><button onClick={exportState} className="action-card"><strong>Export Maintenance Snapshot</strong><span>Simpan kondisi teknis V5.2 untuk audit/troubleshooting.</span></button></div></Card><Card title="Detail storage"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label="LocalStorage keys" value={String(x.localStorageKeys)}/><Metric label="Automation logs" value={String(x.automationLogs)}/><Metric label="Approval lama" value={String(x.oldResolvedApprovals)}/><Metric label="Scheduled reports" value={String(x.scheduledReports)}/></div></Card></div>
}
