'use client'

import { useEffect, useMemo, useState } from 'react'
import { appendAudit, id, money, type Order, type Product } from '../../lib/itemku'
import { cloudAction } from '../../lib/cloud'
import {
  automationNotifications, customerCrm, expectedSettlement, forecastBusiness, generatePoNo, salesForecast, settlementDifference, slaMetrics,
  type AutomationRule, type ChannelRule, type CustomerTag, type DashboardPreferences, type Dispute, type InventoryLedger,
  loadSyncQueue, type NotificationItem, type PurchaseOrder, type Settlement, type Supplier, type SyncState,
} from '../../lib/v4'
import { flushSyncQueue } from '../../lib/sync-queue'

export type V4Ctx = {
  products:Product[]; orders:Order[]; ownerCloud:boolean; flash:(s:string)=>void; hydrateCloud:()=>Promise<void>|void;
  channelRules:ChannelRule[]; suppliers:Supplier[]; purchaseOrders:PurchaseOrder[]; inventoryLedger:InventoryLedger[];
  settlements:Settlement[]; disputes:Dispute[]; automationRules:AutomationRule[]; notifications:NotificationItem[];
  dashboardPreferences:DashboardPreferences; customerTags:CustomerTag[]; syncState:SyncState; online:boolean;
  saveChannelRulesV:(x:ChannelRule[])=>void; saveSuppliersV:(x:Supplier[])=>void; savePurchaseOrdersV:(x:PurchaseOrder[])=>void;
  saveInventoryLedgerV:(x:InventoryLedger[])=>void; saveSettlementsV:(x:Settlement[])=>void; saveDisputesV:(x:Dispute[])=>void;
  saveAutomationRulesV:(x:AutomationRule[])=>void; saveNotificationsV:(x:NotificationItem[])=>void;
  saveDashboardPreferencesV:(x:DashboardPreferences)=>void; saveCustomerTagsV:(x:CustomerTag[])=>void;
  saveProductsV:(x:Product[])=>void; setActive:(s:string)=>void;
}

const fmt=(v?:string)=>v?new Date(v).toLocaleString('id-ID'):'-'
const dateInput=(d=new Date())=>{const z=new Date(d.getTime()-d.getTimezoneOffset()*60000);return z.toISOString().slice(0,16)}

export function ChannelsFeesView(c:V4Ctx){
  const [name,setName]=useState('');const [fee,setFee]=useState(0);const [fixed,setFixed]=useState(0);const [note,setNote]=useState('')
  const add=()=>{if(!name.trim())return c.flash('Nama channel wajib diisi');const now=new Date().toISOString();const exists=c.channelRules.find(x=>x.name.trim().toLowerCase()===name.trim().toLowerCase());const row:ChannelRule={id:exists?.id||id('channel'),name:name.trim(),feePercent:fee,fixedFee:fixed,active:true,note:note.trim(),updatedAt:now};c.saveChannelRulesV(exists?c.channelRules.map(x=>x.id===exists.id?row:x):[...c.channelRules,row]);setName('');setFee(0);setFixed(0);setNote('');c.flash('Aturan fee disimpan')}
  return <div className="space-y-5"><Card title="Channel & Fee Rules" subtitle="Fee transaksi dapat berbeda antara Itemku, WhatsApp, Direct, atau channel lain. Produk tetap menjadi fallback bila channel tidak punya rule."><div className="grid gap-3 md:grid-cols-5"><Field label="Channel" value={name} onChange={setName}/><Num label="Fee %" value={fee} onChange={setFee}/><Num label="Fee tetap" value={fixed} onChange={setFixed}/><Field label="Catatan" value={note} onChange={setNote}/><button onClick={add} className="btn-primary self-end">+ Simpan Rule</button></div></Card><Card title="Aturan aktif"><Table headers={['Channel','Fee','Tetap','Status','Catatan','Aksi']}>{c.channelRules.map(x=><tr key={x.id}><Td><strong>{x.name}</strong></Td><Td>{x.feePercent}%</Td><Td>{money(x.fixedFee)}</Td><Td><Badge tone={x.active?'green':'gray'}>{x.active?'Aktif':'Nonaktif'}</Badge></Td><Td>{x.note||'-'}</Td><Td><button onClick={()=>c.saveChannelRulesV(c.channelRules.map(y=>y.id===x.id?{...y,active:!y.active,updatedAt:new Date().toISOString()}:y))} className="tiny-btn">{x.active?'Nonaktifkan':'Aktifkan'}</button></Td></tr>)}</Table></Card></div>
}

export function SupplierCenterView(c:V4Ctx){
  const [name,setName]=useState('');const [contact,setContact]=useState('');const [note,setNote]=useState('')
  const stats=useMemo(()=>c.suppliers.map(s=>{const pos=c.purchaseOrders.filter(p=>p.supplierId===s.id&&p.status!=='Batal');const productCount=c.products.filter(p=>p.supplier===s.name).length;const spend=pos.reduce((a,b)=>a+b.totalCost,0);const received=pos.filter(p=>p.status==='Diterima').reduce((a,b)=>a+b.qty,0);const profit=c.orders.filter(o=>o.status==='Selesai'&&o.supplierSnapshot===s.name).reduce((a,o)=>a+o.snapshot.profit,0);return {...s,productCount,spend,received,profit,last:pos[0]?.createdAt}}),[c.suppliers,c.purchaseOrders,c.products,c.orders])
  const add=()=>{if(!name.trim())return c.flash('Nama supplier wajib');const now=new Date().toISOString();const row:Supplier={id:id('supplier'),name:name.trim(),contact:contact.trim(),note:note.trim(),active:true,createdAt:now,updatedAt:now};c.saveSuppliersV([...c.suppliers,row]);setName('');setContact('');setNote('');c.flash('Supplier ditambahkan')}
  return <div className="space-y-5"><Card title="Supplier Center" subtitle="Supplier menjadi master data, bukan sekadar teks di produk. Statistik mengambil PO, stok, dan profit historis."><div className="grid gap-3 md:grid-cols-4"><Field label="Nama" value={name} onChange={setName}/><Field label="Kontak" value={contact} onChange={setContact}/><Field label="Catatan" value={note} onChange={setNote}/><button onClick={add} className="btn-primary self-end">+ Tambah Supplier</button></div></Card><Card title="Daftar Supplier"><Table headers={['Supplier','Produk','Pembelian','Unit diterima','Profit','Terakhir','Status']}>{stats.map(s=><tr key={s.id}><Td><strong>{s.name}</strong><small className="block text-muted-foreground">{s.contact||'-'}</small></Td><Td>{s.productCount}</Td><Td>{money(s.spend)}</Td><Td>{s.received}</Td><Td className={s.profit>=0?'text-emerald-700':'text-red-600'}>{money(s.profit)}</Td><Td>{fmt(s.last)}</Td><Td><button onClick={()=>c.saveSuppliersV(c.suppliers.map(x=>x.id===s.id?{...x,active:!x.active,updatedAt:new Date().toISOString()}:x))}><Badge tone={s.active?'green':'gray'}>{s.active?'Aktif':'Arsip'}</Badge></button></Td></tr>)}</Table></Card></div>
}

export function PurchaseOrdersView(c:V4Ctx){
  const [supplierId,setSupplierId]=useState('');const [productId,setProductId]=useState('');const [qty,setQty]=useState(1);const [cost,setCost]=useState(0);const [note,setNote]=useState('')
  const create=()=>{const s=c.suppliers.find(x=>x.id===supplierId),p=c.products.find(x=>x.id===productId);if(!s||!p)return c.flash('Pilih supplier dan produk');if(qty<=0)return c.flash('Qty tidak valid');const now=new Date().toISOString();const row:PurchaseOrder={id:id('po'),poNo:generatePoNo(c.purchaseOrders),supplierId:s.id,supplierName:s.name,productId:p.id,productName:p.name,qty,unitCost:cost,totalCost:qty*cost,status:'Draft',orderedAt:now,note:note.trim(),createdAt:now,updatedAt:now};c.savePurchaseOrdersV([row,...c.purchaseOrders]);setQty(1);setNote('');c.flash('Purchase Order dibuat')}
  const status=(po:PurchaseOrder,next:PurchaseOrder['status'])=>c.savePurchaseOrdersV(c.purchaseOrders.map(x=>x.id===po.id?{...x,status:next,orderedAt:next==='Dipesan'&&x.status==='Draft'?new Date().toISOString():x.orderedAt,updatedAt:new Date().toISOString()}:x))
  const receive=async(po:PurchaseOrder)=>{if(po.status==='Diterima')return;try{if(c.ownerCloud){await cloudAction('receivePurchaseOrder',{purchaseOrderId:po.id});await c.hydrateCloud()}else{const p=c.products.find(x=>x.id===po.productId);if(!p)throw new Error('Produk tidak ditemukan');const before=p.stock,after=before+po.qty,newModal=after?((before*p.modal)+(po.qty*po.unitCost))/after:po.unitCost;c.saveProductsV(c.products.map(x=>x.id===p.id?{...x,stock:after,modal:newModal,supplier:po.supplierName}:x));const led:InventoryLedger={id:id('ledger'),productId:p.id,productName:p.name,delta:po.qty,stockBefore:before,stockAfter:after,reason:'PO',referenceId:po.id,note:po.poNo,createdAt:new Date().toISOString(),actor:'Owner'};c.saveInventoryLedgerV([led,...c.inventoryLedger]);c.savePurchaseOrdersV(c.purchaseOrders.map(x=>x.id===po.id?{...x,status:'Diterima',receivedAt:new Date().toISOString(),updatedAt:new Date().toISOString()}:x))}appendAudit('PO diterima',`${po.poNo} · ${po.productName}`);c.flash('PO diterima, stok bertambah')}catch(e:any){c.flash(e.message||'Gagal menerima PO')}}
  return <div className="space-y-5"><Card title="Purchase Order" subtitle="Alur Draft → Dipesan → Dibayar → Diterima. Saat diterima, stok bertambah dan modal menggunakan weighted average."><div className="grid gap-3 md:grid-cols-6"><Select label="Supplier" value={supplierId} onChange={setSupplierId} options={[['','Pilih'],...c.suppliers.filter(x=>x.active).map(x=>[x.id,x.name])]}/><Select label="Produk" value={productId} onChange={v=>{setProductId(v);setCost(c.products.find(x=>x.id===v)?.modal||0)}} options={[['','Pilih'],...c.products.map(x=>[x.id,`${x.game} · ${x.name}`])]}/><Num label="Qty" value={qty} onChange={setQty}/><Num label="Modal/unit" value={cost} onChange={setCost}/><Field label="Catatan" value={note} onChange={setNote}/><button onClick={create} className="btn-primary self-end">+ Buat PO</button></div></Card><Card title="Riwayat Purchase Order"><Table headers={['PO','Supplier','Produk','Qty','Total','Status','Tanggal','Aksi']}>{c.purchaseOrders.map(po=><tr key={po.id}><Td><strong>{po.poNo}</strong></Td><Td>{po.supplierName}</Td><Td>{po.productName}</Td><Td>{po.qty}</Td><Td>{money(po.totalCost)}</Td><Td><Badge tone={po.status==='Diterima'?'green':po.status==='Batal'?'red':po.status==='Dibayar'?'blue':'amber'}>{po.status}</Badge></Td><Td>{fmt(po.receivedAt||po.orderedAt)}</Td><Td><div className="flex flex-wrap gap-1">{po.status==='Draft'&&<button onClick={()=>status(po,'Dipesan')} className="tiny-btn">Dipesan</button>}{po.status==='Dipesan'&&<button onClick={()=>status(po,'Dibayar')} className="tiny-btn">Dibayar</button>}{['Dipesan','Dibayar'].includes(po.status)&&<button onClick={()=>void receive(po)} className="tiny-btn text-emerald-700">Terima</button>}{po.status!=='Diterima'&&po.status!=='Batal'&&<button onClick={()=>status(po,'Batal')} className="tiny-btn text-red-600">Batal</button>}</div></Td></tr>)}</Table></Card></div>
}

export function InventoryLedgerView(c:V4Ctx){
  const [productId,setProductId]=useState('');const [newStock,setNewStock]=useState(0);const [note,setNote]=useState('Stock opname');const [q,setQ]=useState('')
  const selected=c.products.find(x=>x.id===productId)
  useEffect(()=>{if(selected)setNewStock(selected.stock)},[productId])
  const adjust=async()=>{if(!selected)return c.flash('Pilih produk');if(newStock<0)return c.flash('Stok tidak valid');if(!note.trim())return c.flash('Alasan koreksi wajib');try{if(c.ownerCloud){await cloudAction('adjustStock',{productId:selected.id,newStock,note});await c.hydrateCloud()}else{const led:InventoryLedger={id:id('ledger'),productId:selected.id,productName:selected.name,delta:newStock-selected.stock,stockBefore:selected.stock,stockAfter:newStock,reason:'Adjustment',note:note.trim(),createdAt:new Date().toISOString(),actor:'Owner'};c.saveProductsV(c.products.map(x=>x.id===selected.id?{...x,stock:newStock}:x));c.saveInventoryLedgerV([led,...c.inventoryLedger])}appendAudit('Koreksi stok',`${selected.name}: ${selected.stock} → ${newStock}`);c.flash('Stock adjustment disimpan')}catch(e:any){c.flash(e.message||'Koreksi gagal')}}
  const rows=c.inventoryLedger.filter(x=>`${x.productName} ${x.reason} ${x.referenceId||''}`.toLowerCase().includes(q.toLowerCase()))
  return <div className="space-y-5"><div className="grid gap-5 xl:grid-cols-[.65fr_1.35fr]"><Card title="Stock Adjustment" subtitle="Koreksi hasil stock opname. Alasan wajib dan masuk inventory ledger."><div className="grid gap-3"><Select label="Produk" value={productId} onChange={setProductId} options={[['','Pilih'],...c.products.map(x=>[x.id,`${x.game} · ${x.name} (${x.stock})`])]}/><Num label="Stok aktual" value={newStock} onChange={setNewStock}/><Field label="Alasan" value={note} onChange={setNote}/>{selected&&<p className="rounded-xl bg-muted p-3 text-xs">Sistem {selected.stock} → Aktual <strong>{newStock}</strong> · Selisih <strong>{newStock-selected.stock>=0?'+':''}{newStock-selected.stock}</strong></p>}<button onClick={()=>void adjust()} className="btn-primary">Simpan Koreksi</button></div></Card><Card title="Inventory Ledger" action={<input className="input h-9" placeholder="Cari produk/referensi" value={q} onChange={e=>setQ(e.target.value)}/>}><Table headers={['Tanggal','Produk','Perubahan','Sebelum','Sesudah','Alasan','Referensi','Actor']}>{rows.slice(0,200).map(x=><tr key={x.id}><Td>{fmt(x.createdAt)}</Td><Td>{x.productName}</Td><Td className={x.delta>=0?'text-emerald-700':'text-red-600'}>{x.delta>=0?'+':''}{x.delta}</Td><Td>{x.stockBefore}</Td><Td>{x.stockAfter}</Td><Td>{x.reason}</Td><Td>{x.referenceId||x.note||'-'}</Td><Td>{x.actor}</Td></tr>)}</Table></Card></div></div>
}

export function SettlementView(c:V4Ctx){
  const [channel,setChannel]=useState('Itemku');const [start,setStart]=useState(dateInput(new Date(Date.now()-7*86400000)));const [end,setEnd]=useState(dateInput());const [actual,setActual]=useState(0);const [note,setNote]=useState('')
  const expected=expectedSettlement(c.orders,channel,new Date(start).toISOString(),new Date(end).toISOString())
  const add=()=>{const now=new Date().toISOString();const row:Settlement={id:id('settlement'),channel,periodStart:new Date(start).toISOString(),periodEnd:new Date(end).toISOString(),expectedAmount:expected,actualAmount:actual,status:actual<=0?'Belum Cair':actual>=expected?'Sudah Cair':'Sebagian',paidAt:actual>0?now:undefined,note:note.trim(),createdAt:now,updatedAt:now};c.saveSettlementsV([row,...c.settlements]);setActual(0);setNote('');c.flash('Settlement disimpan')}
  const diff=c.settlements.reduce((a,x)=>a+settlementDifference(x),0)
  return <div className="space-y-5"><section className="grid gap-3 sm:grid-cols-3"><Metric label="Expected seluruh settlement" value={money(c.settlements.reduce((a,x)=>a+x.expectedAmount,0))}/><Metric label="Actual diterima" value={money(c.settlements.reduce((a,x)=>a+x.actualAmount,0))}/><Metric label="Selisih rekonsiliasi" value={money(diff)} tone={diff<0?'bad':'good'}/></section><Card title="Rekonsiliasi Pencairan"><div className="grid gap-3 md:grid-cols-6"><Select label="Channel" value={channel} onChange={setChannel} options={c.channelRules.filter(x=>x.active).map(x=>[x.name,x.name])}/><Field type="datetime-local" label="Mulai" value={start} onChange={setStart}/><Field type="datetime-local" label="Sampai" value={end} onChange={setEnd}/><div className="rounded-xl border p-3 text-xs"><span className="text-muted-foreground">Expected</span><strong className="block text-lg">{money(expected)}</strong></div><Num label="Actual payout" value={actual} onChange={setActual}/><button onClick={add} className="btn-primary self-end">+ Catat Pencairan</button></div><div className="mt-3"><Field label="Catatan" value={note} onChange={setNote}/></div></Card><Card title="Settlement"><Table headers={['Channel','Periode','Expected','Actual','Selisih','Status','Cair']}>{c.settlements.map(x=><tr key={x.id}><Td>{x.channel}</Td><Td>{new Date(x.periodStart).toLocaleDateString('id-ID')} – {new Date(x.periodEnd).toLocaleDateString('id-ID')}</Td><Td>{money(x.expectedAmount)}</Td><Td>{money(x.actualAmount)}</Td><Td className={settlementDifference(x)<0?'text-red-600':'text-emerald-700'}>{money(settlementDifference(x))}</Td><Td><Badge tone={x.status==='Sudah Cair'?'green':x.status==='Sebagian'?'amber':'gray'}>{x.status}</Badge></Td><Td>{fmt(x.paidAt)}</Td></tr>)}</Table></Card></div>
}

export function DisputeSlaView(c:V4Ctx){
  const [orderId,setOrderId]=useState('');const [reason,setReason]=useState('');const [chronology,setChronology]=useState('')
  const sla=slaMetrics(c.orders,c.dashboardPreferences.slaMinutes)
  const create=()=>{const o=c.orders.find(x=>x.id===orderId);if(!o)return c.flash('Pilih order');if(!reason.trim())return c.flash('Alasan wajib');const now=new Date().toISOString();const row:Dispute={id:id('dispute'),orderId:o.id,invoiceNo:o.invoiceNo,buyerIdentifier:o.buyerIdentifier,reason:reason.trim(),chronology:chronology.trim(),status:'Terbuka',assignedWorker:o.assignedWorker,createdAt:now,updatedAt:now};c.saveDisputesV([row,...c.disputes]);setReason('');setChronology('');c.flash('Kasus dispute dibuat')}
  const setStatus=(d:Dispute,status:Dispute['status'])=>c.saveDisputesV(c.disputes.map(x=>x.id===d.id?{...x,status,updatedAt:new Date().toISOString(),resolvedAt:status==='Selesai'||status==='Ditutup'?new Date().toISOString():x.resolvedAt}:x))
  return <div className="space-y-5"><section className="grid gap-3 sm:grid-cols-4"><Metric label="SLA target" value={`${c.dashboardPreferences.slaMinutes} menit`}/><Metric label="Rata-rata selesai" value={`${sla.avgMinutes.toFixed(1)} menit`} tone={sla.avgMinutes<=c.dashboardPreferences.slaMinutes?'good':'warn'}/><Metric label="Sesuai SLA" value={`${sla.withinSlaPct.toFixed(1)}%`} tone={sla.withinSlaPct>=90?'good':'warn'}/><Metric label="Dispute terbuka" value={String(c.disputes.filter(x=>!['Selesai','Ditutup'].includes(x.status)).length)} tone="warn"/></section><Card title="Buat Kasus / Kendala"><div className="grid gap-3 md:grid-cols-4"><Select label="Order" value={orderId} onChange={setOrderId} options={[['','Pilih'],...c.orders.slice(0,100).map(o=>[o.id,`${o.invoiceNo} · ${o.buyerIdentifier}`])]}/><Field label="Alasan" value={reason} onChange={setReason}/><Field label="Kronologi" value={chronology} onChange={setChronology}/><button onClick={create} className="btn-primary self-end">+ Buat Kasus</button></div></Card><Card title="Dispute & Kendala"><Table headers={['Invoice','Pembeli','Alasan','Status','Worker','Dibuat','Aksi']}>{c.disputes.map(d=><tr key={d.id}><Td>{d.invoiceNo}</Td><Td>{d.buyerIdentifier}</Td><Td><strong>{d.reason}</strong><small className="block text-muted-foreground">{d.chronology||'-'}</small></Td><Td><Badge tone={d.status==='Selesai'||d.status==='Ditutup'?'green':d.status==='Terbuka'?'red':'amber'}>{d.status}</Badge></Td><Td>{d.assignedWorker||'-'}</Td><Td>{fmt(d.createdAt)}</Td><Td><select className="input h-8" value={d.status} onChange={e=>setStatus(d,e.target.value as Dispute['status'])}>{['Terbuka','Menunggu Pembeli','Menunggu Seller','Selesai','Ditutup'].map(x=><option key={x}>{x}</option>)}</select></Td></tr>)}</Table></Card></div>
}

export function AutomationForecastView(c:V4Ctx){
  const forecast=useMemo(()=>salesForecast(c.products,c.orders,30,c.dashboardPreferences.forecastDays),[c.products,c.orders,c.dashboardPreferences.forecastDays]);const business=forecastBusiness(c.orders,30)
  const run=async()=>{const generated=automationNotifications(c.products,c.orders,c.automationRules);const oldRead=new Map(c.notifications.map(n=>[`${n.kind}|${n.entityId||''}|${n.title}`,n.read]));const rows:NotificationItem[]=generated.map((x:any)=>({...x,read:oldRead.get(`${x.kind}|${x.entityId||''}|${x.title}`)||false}));c.saveNotificationsV(rows);if('Notification'in window&&Notification.permission==='granted'&&rows.some(x=>!x.read&&['danger','warn'].includes(x.level))){const reg=await navigator.serviceWorker?.getRegistration();void reg?.showNotification('Itemku Profit V4',{body:`${rows.filter(x=>!x.read).length} notifikasi operasional perlu diperiksa.`,icon:'/icon-192.png'})}c.flash(`${rows.length} notifikasi diperbarui`)}
  const permission=async()=>{if(!('Notification'in window))return c.flash('Browser tidak mendukung notifikasi');const p=await Notification.requestPermission();c.flash(`Izin notifikasi: ${p}`)}
  return <div className="space-y-5"><section className="grid gap-3 sm:grid-cols-4"><Metric label="Proyeksi profit/bulan" value={money(business.projectedMonthlyProfit)} tone="good"/><Metric label="Proyeksi omzet/bulan" value={money(business.projectedMonthlyRevenue)}/><Metric label="Produk perlu restock" value={String(forecast.filter(x=>x.recommendedRestock>0).length)} tone="warn"/><Metric label="Pending notification" value={String(c.notifications.filter(x=>!x.read).length)} tone="warn"/></section><Card title="Automation Rules" action={<div className="flex gap-2"><button onClick={()=>void permission()} className="btn-secondary">Izin Push</button><button onClick={()=>void run()} className="btn-primary">Jalankan Rules</button></div>}><Table headers={['Rule','Threshold','Status','Aksi']}>{c.automationRules.map(r=><tr key={r.id}><Td><strong>{r.label}</strong><small className="block text-muted-foreground">{r.kind}</small></Td><Td><input className="input h-8 w-28" type="number" value={r.threshold} onChange={e=>c.saveAutomationRulesV(c.automationRules.map(x=>x.id===r.id?{...x,threshold:Number(e.target.value)||0,updatedAt:new Date().toISOString()}:x))}/></Td><Td><Badge tone={r.enabled?'green':'gray'}>{r.enabled?'Aktif':'Mati'}</Badge></Td><Td><button className="tiny-btn" onClick={()=>c.saveAutomationRulesV(c.automationRules.map(x=>x.id===r.id?{...x,enabled:!x.enabled,updatedAt:new Date().toISOString()}:x))}>{r.enabled?'Nonaktifkan':'Aktifkan'}</button></Td></tr>)}</Table></Card><Card title="Smart Restock Recommendation" subtitle={`Berdasarkan rata-rata 30 hari dan target coverage ${c.dashboardPreferences.forecastDays} hari.`}><Table headers={['Produk','Game','Rata-rata/hari','Stok','Estimasi habis','Saran restock']}>{forecast.slice(0,50).map(x=><tr key={x.productId}><Td>{x.productName}</Td><Td>{x.game}</Td><Td>{x.avgDaily.toFixed(2)}</Td><Td>{x.stock}</Td><Td>{x.daysLeft===null?'Belum ada penjualan':`${x.daysLeft.toFixed(1)} hari`}</Td><Td className={x.recommendedRestock>0?'font-bold text-amber-700':''}>{x.recommendedRestock>0?`+${x.recommendedRestock}`:'Aman'}</Td></tr>)}</Table></Card></div>
}

export function CrmV2View(c:V4Ctx){
  const [q,setQ]=useState('');const [buyer,setBuyer]=useState('');const [tag,setTag]=useState('VIP');const rows=customerCrm(c.orders,c.customerTags).filter(x=>x.buyer.toLowerCase().includes(q.toLowerCase()))
  const addTag=()=>{if(!buyer.trim()||!tag.trim())return;const existing=c.customerTags.find(x=>x.buyerIdentifier.toLowerCase()===buyer.trim().toLowerCase());const row:CustomerTag={id:existing?.id||id('tag'),buyerIdentifier:buyer.trim(),tags:[...new Set([...(existing?.tags||[]),tag.trim()])]};c.saveCustomerTagsV(existing?c.customerTags.map(x=>x.id===existing.id?row:x):[...c.customerTags,row]);c.flash('Tag pelanggan disimpan')}
  return <div className="space-y-5"><Card title="Customer CRM V2" subtitle="Tag otomatis: Pelanggan Baru, Repeat Buyer, VIP, dan Sering Refund. Tag manual dapat ditambahkan Owner." action={<input className="input h-9" placeholder="Cari customer" value={q} onChange={e=>setQ(e.target.value)}/>}><Table headers={['Customer','Order','Total belanja','AOV','Refund','Tag','Terakhir']}>{rows.map(x=><tr key={x.buyer}><Td><strong>{x.buyer}</strong></Td><Td>{x.orders}</Td><Td>{money(x.spend)}</Td><Td>{money(x.aov)}</Td><Td>{x.refunds}</Td><Td><div className="flex flex-wrap gap-1">{x.tags.map(t=><Badge key={t} tone={t==='VIP'?'green':t==='Sering Refund'?'red':'blue'}>{t}</Badge>)}</div></Td><Td>{fmt(x.lastAt)}</Td></tr>)}</Table></Card><Card title="Tambah Tag Manual"><div className="grid gap-3 md:grid-cols-3"><Field label="Username/User ID" value={buyer} onChange={setBuyer}/><Field label="Tag" value={tag} onChange={setTag}/><button onClick={addTag} className="btn-primary self-end">+ Simpan Tag</button></div></Card></div>
}

export function NotificationCenterView(c:V4Ctx){
  const unread=c.notifications.filter(x=>!x.read).length
  const mark=(idv:string)=>c.saveNotificationsV(c.notifications.map(x=>x.id===idv?{...x,read:true}:x));const all=()=>c.saveNotificationsV(c.notifications.map(x=>({...x,read:true})))
  return <Card title="Notification Center" subtitle={`${unread} belum dibaca`} action={<button className="btn-secondary" onClick={all}>Tandai semua dibaca</button>}><div className="space-y-2">{c.notifications.map(n=><button key={n.id} onClick={()=>mark(n.id)} className={`w-full rounded-xl border p-3 text-left ${n.read?'opacity-60':'bg-card shadow-sm'}`}><div className="flex items-center justify-between gap-2"><strong className="text-sm">{n.title}</strong><Badge tone={n.level==='danger'?'red':n.level==='warn'?'amber':n.level==='success'?'green':'blue'}>{n.level}</Badge></div><p className="mt-1 text-xs text-muted-foreground">{n.detail}</p><small className="mt-2 block text-muted-foreground">{fmt(n.createdAt)}</small></button>)}{!c.notifications.length&&<Empty text="Jalankan Automation Rules untuk membuat notifikasi."/>}</div></Card>
}

export function DashboardCustomizeView(c:V4Ctx){
  const cards=[['profit','Profit'],['revenue','Omzet'],['orders','Order'],['stock','Stok'],['sla','SLA'],['forecast','Forecast']];const toggle=(key:string)=>{const v=c.dashboardPreferences.visibleCards.includes(key)?c.dashboardPreferences.visibleCards.filter(x=>x!==key):[...c.dashboardPreferences.visibleCards,key];c.saveDashboardPreferencesV({...c.dashboardPreferences,visibleCards:v})}
  return <div className="space-y-5"><Card title="Dashboard Customization" subtitle="Pilih kartu yang ingin diprioritaskan dan parameter operasional V4."><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{cards.map(([k,l])=><label key={k} className="flex items-center gap-3 rounded-xl border p-4 text-sm font-bold"><input type="checkbox" checked={c.dashboardPreferences.visibleCards.includes(k)} onChange={()=>toggle(k)}/>{l}</label>)}</div><div className="mt-5 grid gap-3 sm:grid-cols-2"><Num label="Target SLA (menit)" value={c.dashboardPreferences.slaMinutes} onChange={v=>c.saveDashboardPreferencesV({...c.dashboardPreferences,slaMinutes:Math.max(1,v)})}/><Num label="Target coverage restock (hari)" value={c.dashboardPreferences.forecastDays} onChange={v=>c.saveDashboardPreferencesV({...c.dashboardPreferences,forecastDays:Math.max(1,v)})}/></div></Card></div>
}

export function HealthImportView(c:V4Ctx){
  const [sw,setSw]=useState('Memeriksa...');const [importStatus,setImportStatus]=useState('');const pending=loadSyncQueue();const lastError=pending.find(x=>x.lastError)?.lastError||''
  useEffect(()=>{void navigator.serviceWorker?.getRegistration().then(r=>setSw(r?'Aktif':'Belum aktif')).catch(()=>setSw('Tidak tersedia'))},[])
  const importCsv=async(file:File)=>{try{const text=await file.text();const lines=text.split(/\r?\n/).filter(Boolean);if(lines.length<2)throw new Error('CSV kosong');const headers=lines[0].split(',').map(x=>x.trim().replace(/^"|"$/g,'').toLowerCase());const idx=(...names:string[])=>names.map(n=>headers.indexOf(n)).find(i=>i>=0)??-1;const nameI=idx('nama','name','produk'),gameI=idx('game'),catI=idx('kategori','category'),skuI=idx('sku'),stockI=idx('stok','stock'),modalI=idx('modal'),priceI=idx('harga','price'),supplierI=idx('supplier');if(nameI<0)throw new Error('Kolom nama/produk tidak ditemukan');const parse=(line:string)=>{const out:string[]=[];let cur='',quote=false;for(let i=0;i<line.length;i++){const ch=line[i];if(ch==='"'){if(quote&&line[i+1]==='"'){cur+='"';i++}else quote=!quote}else if(ch===','&&!quote){out.push(cur);cur=''}else cur+=ch}out.push(cur);return out};const now=new Date().toISOString();const next=[...c.products];let count=0;for(const line of lines.slice(1)){const a=parse(line);const name=(a[nameI]||'').trim();if(!name)continue;const sku=skuI>=0?(a[skuI]||'').trim():'';const existing=next.find(x=>(sku&&x.sku===sku)||(!sku&&x.name.toLowerCase()===name.toLowerCase()));const row:Product={...(existing||{id:id('product'),reorderPoint:5,fee:10,fixed:0,other:0,target:20,stockSince:now,discountEnabled:false,discountPrice:0,active:true}),name,game:gameI>=0?(a[gameI]||'Roblox').trim():'Roblox',category:catI>=0?(a[catI]||'Item').trim():'Item',sku,supplier:supplierI>=0?(a[supplierI]||'').trim():'',stock:Math.max(0,Number(a[stockI])||0),modal:Math.max(0,Number(a[modalI])||0),price:Math.max(0,Number(a[priceI])||0)} as Product;if(existing)next[next.indexOf(existing)]=row;else next.push(row);count++}c.saveProductsV(next);setImportStatus(`${count} baris produk diproses`);c.flash('Import CSV selesai')}catch(e:any){setImportStatus(e.message||'Import gagal')}}
  const downloadTemplate=()=>{const text='nama,game,kategori,sku,stok,modal,harga,supplier\n1M Coins,Fish It!,Coins,FISH-1M,10,2500,4000,Supplier A';const blob=new Blob([text],{type:'text/csv'});const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download='template-import-produk-v4.csv';a.click();URL.revokeObjectURL(u)}
  return <div className="space-y-5"><section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><Metric label="Versi" value="V5.2"/><Metric label="Internet" value={c.online?'Online':'Offline'} tone={c.online?'good':'warn'}/><Metric label="Sync" value={c.syncState} tone={c.syncState==='synced'?'good':c.syncState==='error'?'bad':'warn'}/><Metric label="Pending Sync" value={String(pending.length)} tone={pending.length?'warn':'good'}/><Metric label="Service Worker" value={sw}/><Metric label="Mode Cloud" value={c.ownerCloud?'Owner Cloud':'Local'}/></section>{lastError&&<Card title="Sync Error Terakhir"><p className="text-xs text-red-600">{lastError}</p><button className="btn-secondary mt-3" onClick={()=>void flushSyncQueue(()=>{})}>Coba Sync Lagi</button></Card>}<Card title="Import Produk CSV" subtitle="Mendukung mapping sederhana berdasarkan nama header. SKU yang sama akan di-update; data lain ditambahkan."><div className="flex flex-wrap gap-2"><button className="btn-secondary" onClick={downloadTemplate}>Download Template</button><label className="btn-primary cursor-pointer">Import CSV<input type="file" accept=".csv,text/csv" className="hidden" onChange={e=>{const f=e.target.files?.[0];if(f)void importCsv(f)}}/></label></div>{importStatus&&<p className="mt-3 text-xs text-muted-foreground">{importStatus}</p>}</Card><Card title="Recovery Checklist"><div className="grid gap-2 text-xs text-muted-foreground"><p>• Sync queue menyimpan perubahan saat koneksi terputus dan mencoba ulang ketika online.</p><p>• Untuk backup penuh, tetap gunakan menu Backup & Export sebelum migrasi schema.</p><p>• Jalankan <code>supabase/schema-v5.2.sql</code> sebelum mengaktifkan modul cloud V5.2.</p><p>• Produk dengan histori transaksi sebaiknya dinonaktifkan/diarsipkan, bukan dihapus permanen.</p></div></Card></div>
}

export function V4QuickDashboard(c:V4Ctx){const sla=useMemo(()=>slaMetrics(c.orders,c.dashboardPreferences.slaMinutes),[c.orders,c.dashboardPreferences.slaMinutes]);const f=useMemo(()=>salesForecast(c.products,c.orders,30,c.dashboardPreferences.forecastDays),[c.products,c.orders,c.dashboardPreferences.forecastDays]);const b=useMemo(()=>forecastBusiness(c.orders,30),[c.orders]);const visible=c.dashboardPreferences.visibleCards;const cards=[visible.includes('profit')&&<Metric key="p" label="Forecast profit" value={money(b.projectedMonthlyProfit)} tone="good"/>,visible.includes('revenue')&&<Metric key="r" label="Forecast omzet" value={money(b.projectedMonthlyRevenue)}/>,visible.includes('orders')&&<Metric key="o" label="Order aktif" value={String(c.orders.filter(o=>['Baru','Diproses'].includes(o.status)).length)}/>,visible.includes('stock')&&<Metric key="s" label="Stok kritis" value={String(c.products.filter(p=>p.active&&p.stock<=p.reorderPoint).length)} tone="warn"/>,visible.includes('sla')&&<Metric key="sl" label="Sesuai SLA" value={`${sla.withinSlaPct.toFixed(1)}%`} tone={sla.withinSlaPct>=90?'good':'warn'}/>,visible.includes('forecast')&&<Metric key="f" label="Perlu restock" value={String(f.filter(x=>x.recommendedRestock>0).length)} tone="warn"/>].filter(Boolean);return <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-6">{cards}</section>}

function Card({title,subtitle,children,action}:{title:string;subtitle?:string;children:React.ReactNode;action?:React.ReactNode}){return <section className="rounded-2xl border bg-card p-5 shadow-sm"><div className="mb-4 flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-base font-bold">{title}</h2>{subtitle&&<p className="mt-1 max-w-3xl text-xs leading-relaxed text-muted-foreground">{subtitle}</p>}</div>{action}</div>{children}</section>}
function Metric({label,value,tone}:{label:string;value:string;tone?:'good'|'bad'|'warn'}){const cls=tone==='good'?'text-emerald-700':tone==='bad'?'text-red-600':tone==='warn'?'text-amber-700':'';return <div className="rounded-xl border bg-card p-4"><span className="block text-xs text-muted-foreground">{label}</span><strong className={`mt-1 block text-xl ${cls}`}>{value}</strong></div>}
function Field({label,value,onChange,type='text'}:{label:string;value:string;onChange:(v:string)=>void;type?:string}){return <label className="grid gap-1.5 text-xs font-semibold">{label}<input type={type} value={value} onChange={e=>onChange(e.target.value)} className="input h-10"/></label>}
function Num({label,value,onChange}:{label:string;value:number;onChange:(v:number)=>void}){return <label className="grid gap-1.5 text-xs font-semibold">{label}<input type="number" min="0" value={value} onChange={e=>onChange(Math.max(0,Number(e.target.value)||0))} className="input h-10"/></label>}
function Select({label,value,onChange,options}:{label:string;value:string;onChange:(v:string)=>void;options:(string[]|readonly string[])[]}){return <label className="grid gap-1.5 text-xs font-semibold">{label}<select value={value} onChange={e=>onChange(e.target.value)} className="input h-10">{options.map((x:any)=><option key={x[0]} value={x[0]}>{x[1]}</option>)}</select></label>}
function Table({headers,children}:{headers:string[];children:React.ReactNode}){return <div className="overflow-x-auto"><table className="w-full min-w-[820px] border-collapse text-left text-xs"><thead><tr>{headers.map(h=><th key={h} className="border-b px-3 py-2.5 font-semibold text-muted-foreground">{h}</th>)}</tr></thead><tbody>{children}</tbody></table></div>}
function Td({children,className=''}:{children:React.ReactNode;className?:string}){return <td className={`border-b px-3 py-3 align-top ${className}`}>{children}</td>}
function Badge({children,tone='gray'}:{children:React.ReactNode;tone?:string}){const cls=tone==='green'?'bg-emerald-100 text-emerald-800 dark:bg-emerald-950 dark:text-emerald-200':tone==='red'?'bg-red-100 text-red-700 dark:bg-red-950 dark:text-red-200':tone==='amber'?'bg-amber-100 text-amber-800 dark:bg-amber-950 dark:text-amber-200':tone==='blue'?'bg-blue-100 text-blue-700 dark:bg-blue-950 dark:text-blue-200':'bg-muted text-muted-foreground';return <span className={`inline-flex rounded-full px-2 py-1 text-[10px] font-bold ${cls}`}>{children}</span>}
function Empty({text}:{text:string}){return <p className="rounded-xl border border-dashed p-8 text-center text-sm text-muted-foreground">{text}</p>}
