'use client'

import { useMemo, useState } from 'react'
import { appendAudit, calculateProduct, money, type Expense, type Order, type OrderStatus, type Product, type Worker } from '../../lib/itemku'
import { cloudAction } from '../../lib/cloud'
import { chooseWorkerForOrder, priceSafety, productPerformance, reportSummary, smartRestock, workerQueue } from '../../lib/v41'

export type V41Ctx = {
  products: Product[]
  orders: Order[]
  expenses: Expense[]
  workers: Worker[]
  ownerCloud: boolean
  saveProductsV: (x: Product[])=>void
  saveOrdersV: (x: Order[])=>void
  hydrateCloud: ()=>Promise<void>|void
  flash: (s:string)=>void
}

const fmt=(v?:string)=>v?new Date(v).toLocaleString('id-ID'):'-'
const pct=(n:number)=>`${Number.isFinite(n)?n.toFixed(1):'0.0'}%`

export function OrderKanbanView(c:V41Ctx){
  const [busy,setBusy]=useState('')
  const columns:OrderStatus[]=['Baru','Diproses','Menunggu','Selesai']
  const active=c.orders.filter(o=>columns.includes(o.status)).sort((a,b)=>new Date(b.createdAt).getTime()-new Date(a.createdAt).getTime())
  const move=async(order:Order,status:OrderStatus)=>{
    if(order.status===status)return
    setBusy(order.id)
    try{
      if(c.ownerCloud){await cloudAction('transitionOrder',{orderId:order.id,status});await c.hydrateCloud()}
      else{
        const now=new Date().toISOString()
        const updated:Order={...order,status,processingAt:(status==='Diproses'||status==='Menunggu'||status==='Selesai')?(order.processingAt||now):order.processingAt,completedAt:status==='Selesai'?now:undefined,updatedAt:now}
        c.saveOrdersV(c.orders.map(o=>o.id===order.id?updated:o));appendAudit(`Kanban → ${status}`,`${order.invoiceNo} · ${order.productName}`)
      }
      c.flash(`Order dipindah ke ${status}`)
    }catch(e:any){c.flash(e.message||'Gagal mengubah status')}finally{setBusy('')}
  }
  const prev=(s:OrderStatus)=>s==='Selesai'?'Menunggu':s==='Menunggu'?'Diproses':s==='Diproses'?'Baru':null
  const next=(s:OrderStatus)=>s==='Baru'?'Diproses':s==='Diproses'?'Menunggu':s==='Menunggu'?'Selesai':null
  return <div className="space-y-4"><section className="grid gap-3 sm:grid-cols-4">{columns.map(s=><Metric key={s} label={s} value={String(active.filter(o=>o.status===s).length)} tone={s==='Baru'?'warn':s==='Selesai'?'good':undefined}/>)}</section><div className="grid gap-4 xl:grid-cols-4">{columns.map(status=><section key={status} className="rounded-2xl border bg-muted/20 p-3"><div className="mb-3 flex items-center justify-between"><strong className="text-sm">{status}</strong><Badge tone={status==='Selesai'?'green':status==='Menunggu'?'amber':status==='Diproses'?'blue':'gray'}>{active.filter(o=>o.status===status).length}</Badge></div><div className="space-y-3">{active.filter(o=>o.status===status).map(o=><article key={o.id} className="rounded-xl border bg-card p-3 shadow-sm"><div className="flex items-start justify-between gap-2"><div><strong className="text-sm">{o.productName} × {o.qty}</strong><p className="mt-1 text-[10px] text-muted-foreground">{o.invoiceNo} · {o.game}</p></div><span className="text-[10px] text-muted-foreground">{fmt(o.createdAt)}</span></div><div className="mt-3 grid gap-1 text-xs"><span>Pembeli: <strong>{o.buyerIdentifier}</strong></span><span>Worker: <strong>{o.assignedWorker||'Belum ditugaskan'}</strong></span></div><div className="mt-3 flex gap-2">{prev(status)&&<button disabled={busy===o.id} className="tiny-btn flex-1" onClick={()=>void move(o,prev(status)!)}>← {prev(status)}</button>}{next(status)&&<button disabled={busy===o.id} className="tiny-btn flex-1" onClick={()=>void move(o,next(status)!)}>{next(status)} →</button>}</div></article>)}{!active.some(o=>o.status===status)&&<Empty text="Kosong"/>}</div></section>)}</div></div>
}

export function SmartRestockV41View(c:V41Ctx){
  const [coverage,setCoverage]=useState(14);const [lead,setLead]=useState(3)
  const rows=useMemo(()=>smartRestock(c.products,c.orders,coverage,lead),[c.products,c.orders,coverage,lead])
  return <div className="space-y-5"><Card title="Smart Restock V4.1" subtitle="Menggabungkan kecepatan penjualan 7/14/30 hari, stok sekarang, lead time, dan safety buffer 25%." action={<div className="flex gap-2"><MiniNumber label="Coverage" value={coverage} onChange={setCoverage}/><MiniNumber label="Lead" value={lead} onChange={setLead}/></div>}><Table headers={['Produk','Avg 7H','Avg 14H','Avg 30H','Weighted/hari','Stok','Estimasi habis','Saran','Urgensi']}>{rows.map(x=><tr key={x.productId}><Td><strong>{x.productName}</strong><small className="block text-muted-foreground">{x.game}</small></Td><Td>{x.avg7.toFixed(2)}</Td><Td>{x.avg14.toFixed(2)}</Td><Td>{x.avg30.toFixed(2)}</Td><Td><strong>{x.weightedDaily.toFixed(2)}</strong></Td><Td>{x.stock}</Td><Td>{x.daysLeft===null?'Belum cukup data':`${x.daysLeft.toFixed(1)} hari`}</Td><Td className={x.recommendedRestock?'font-black text-amber-700':''}>{x.recommendedRestock?`+${x.recommendedRestock}`:'Aman'}</Td><Td><Badge tone={x.urgency==='Kritis'?'red':x.urgency==='Segera'?'amber':x.urgency==='Pantau'?'blue':'green'}>{x.urgency}</Badge></Td></tr>)}</Table></Card></div>
}

export function ProductScoreView(c:V41Ctx){
  const rows=useMemo(()=>productPerformance(c.products,c.orders),[c.products,c.orders])
  const top=rows.filter(x=>x.score>=80).length, weak=rows.filter(x=>x.score<40).length
  return <div className="space-y-5"><section className="grid gap-3 sm:grid-cols-3"><Metric label="Produk dianalisis" value={String(rows.length)}/><Metric label="Perbesar stok" value={String(top)} tone="good"/><Metric label="Perlu evaluasi" value={String(weak)} tone={weak?'warn':undefined}/></section><Card title="Product Performance Score" subtitle="Skor 0–100 berdasarkan penjualan 30 hari, margin, refund, serta kesehatan dan umur stok."><Table headers={['Produk','Skor','Rekomendasi','Terjual 30H','Profit 30H','Margin','Refund','Umur stok','Alasan']}>{rows.map(x=><tr key={x.productId}><Td><strong>{x.productName}</strong><small className="block text-muted-foreground">{x.game}</small></Td><Td><strong className={x.score>=80?'text-emerald-700':x.score<40?'text-red-600':'text-amber-700'}>{x.score}/100</strong></Td><Td><Badge tone={x.label==='Perbesar stok'?'green':x.label==='Kurangi stok'?'red':x.label==='Pantau'?'amber':'blue'}>{x.label}</Badge></Td><Td>{x.sold30}</Td><Td>{money(x.profit30)}</Td><Td>{pct(x.marginPct)}</Td><Td>{pct(x.refundRate*100)}</Td><Td>{x.agingDays.toFixed(0)} hari</Td><Td>{x.reasons.join(' · ')}</Td></tr>)}</Table></Card></div>
}

export function ProfitSimulatorView(){
  const [modal,setModal]=useState(2500),[price,setPrice]=useState(4000),[fee,setFee]=useState(10),[fixed,setFixed]=useState(0),[other,setOther]=useState(0),[target,setTarget]=useState(20),[qty,setQty]=useState(10)
  const result=priceSafety({modal,price,fee,fixed,other,target},price,Math.max(1,qty)).calc
  const unit=priceSafety({modal,price,fee,fixed,other,target},price,1)
  const totalCapital=modal*Math.max(1,qty),totalProfit=result.profit
  return <div className="grid gap-5 xl:grid-cols-[1fr_1fr]"><Card title="Profit Simulator" subtitle="Coba harga sebelum membeli stok atau mengubah listing Itemku."><div className="grid gap-3 sm:grid-cols-2"><Num label="Modal / unit" value={modal} onChange={setModal}/><Num label="Harga jual" value={price} onChange={setPrice}/><Num label="Fee %" value={fee} onChange={setFee}/><Num label="Biaya tetap/order" value={fixed} onChange={setFixed}/><Num label="Biaya lain/unit" value={other} onChange={setOther}/><Num label="Target margin %" value={target} onChange={setTarget}/><Num label="Jumlah stok/order simulasi" value={qty} onChange={setQty}/></div>{unit.danger&&<Warning tone="bad">Harga berada di bawah BEP. Potensi rugi sekitar {money(Math.abs(unit.calc.profit))} per unit.</Warning>}{!unit.danger&&unit.belowTarget&&<Warning tone="warn">Masih profit, tetapi belum mencapai target margin {target}%.</Warning>}{!unit.danger&&!unit.belowTarget&&<Warning tone="good">Harga berada di zona aman sesuai target saat ini.</Warning>}</Card><Card title="Hasil Simulasi"><div className="grid gap-3 sm:grid-cols-2"><Metric label="BEP / unit" value={money(unit.minimumNoLoss)} tone="warn"/><Metric label="Harga target" value={money(unit.targetSafe)} tone="good"/><Metric label="Profit / unit" value={money(unit.calc.profit)} tone={unit.calc.profit>=0?'good':'bad'}/><Metric label="Margin" value={pct(unit.calc.margin)}/><Metric label="ROI" value={pct(unit.calc.roi)}/><Metric label="Total modal" value={money(totalCapital)}/><Metric label="Total omzet" value={money(result.revenue)}/><Metric label="Total profit" value={money(totalProfit)} tone={totalProfit>=0?'good':'bad'}/></div></Card></div>
}

export function BulkEditProductsView(c:V41Ctx){
  const [selected,setSelected]=useState<string[]>([]);const [supplier,setSupplier]=useState('');const [category,setCategory]=useState('');const [fee,setFee]=useState('');const [markup,setMarkup]=useState('');const [active,setActive]=useState<'keep'|'on'|'off'>('keep');const [q,setQ]=useState('')
  const rows=c.products.filter(p=>`${p.game} ${p.name} ${p.sku}`.toLowerCase().includes(q.toLowerCase()))
  const toggle=(id:string)=>setSelected(x=>x.includes(id)?x.filter(v=>v!==id):[...x,id])
  const apply=()=>{if(!selected.length)return c.flash('Pilih minimal satu produk');const feeN=fee.trim()===''?null:Math.max(0,Number(fee)||0);const markupN=markup.trim()===''?null:Number(markup)||0;const now=new Date().toISOString();const next=c.products.map(p=>{if(!selected.includes(p.id))return p;let price=p.price;if(markupN!==null)price=Math.max(0,Math.round(p.price*(1+markupN/100)));const updated={...p,supplier:supplier.trim()||p.supplier,category:category.trim()||p.category,fee:feeN===null?p.fee:feeN,price,active:active==='keep'?p.active:active==='on',updatedAt:now};const safe=priceSafety(updated,updated.price,1);return safe.danger?{...updated,price:Math.ceil(safe.minimumNoLoss)}:updated});c.saveProductsV(next);appendAudit('Bulk edit produk',`${selected.length} produk diperbarui`);c.flash(`${selected.length} produk diperbarui; harga rugi otomatis dinaikkan minimal ke BEP`);setSelected([])}
  return <div className="space-y-5"><Card title="Bulk Edit Produk" subtitle="Ubah supplier, kategori, fee, status, atau markup harga untuk banyak SKU sekaligus. Margin Guard mencegah harga baru jatuh di bawah BEP."><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><Field label="Supplier baru (opsional)" value={supplier} onChange={setSupplier}/><Field label="Kategori baru (opsional)" value={category} onChange={setCategory}/><Field label="Fee % (opsional)" value={fee} onChange={setFee} type="number"/><Field label="Markup harga %" value={markup} onChange={setMarkup} type="number"/><label className="grid gap-1.5 text-xs font-semibold">Status<select className="input h-10" value={active} onChange={e=>setActive(e.target.value as any)}><option value="keep">Tidak diubah</option><option value="on">Aktif</option><option value="off">Nonaktif</option></select></label></div><div className="mt-4 flex flex-wrap gap-2"><button className="btn-secondary" onClick={()=>setSelected(rows.map(p=>p.id))}>Pilih hasil filter</button><button className="btn-secondary" onClick={()=>setSelected([])}>Kosongkan</button><button className="btn-primary" onClick={apply}>Terapkan ke {selected.length} produk</button></div></Card><Card title="Pilih Produk" action={<input className="input h-9 w-60" placeholder="Cari game / produk / SKU" value={q} onChange={e=>setQ(e.target.value)}/>}><Table headers={['Pilih','Produk','SKU','Stok','Modal','Harga','Profit']}>{rows.map(p=>{const calc=calculateProduct(p);return <tr key={p.id}><Td><input type="checkbox" checked={selected.includes(p.id)} onChange={()=>toggle(p.id)}/></Td><Td><strong>{p.name}</strong><small className="block text-muted-foreground">{p.game} · {p.category}</small></Td><Td>{p.sku||'-'}</Td><Td>{p.stock}</Td><Td>{money(p.modal)}</Td><Td>{money(p.price)}</Td><Td className={calc.profit>=0?'text-emerald-700':'text-red-600'}>{money(calc.profit)}</Td></tr>})}</Table></Card></div>
}

export function WorkerQueueView(c:V41Ctx){
  const [busy,setBusy]=useState(false)
  const queue=useMemo(()=>workerQueue(c.workers,c.orders),[c.workers,c.orders])
  const eligible=c.orders.filter(o=>o.status==='Baru'&&!o.assignedWorkerId&&!o.assignedWorker)
  const assign=async(order:Order,worker:Worker,refresh=true)=>{try{if(c.ownerCloud){if(!worker.cloudUserId)throw new Error(`Worker ${worker.name} belum memiliki UUID cloud`);await cloudAction('assignOrder',{orderId:order.id,workerId:worker.cloudUserId});if(refresh)await c.hydrateCloud()}else{const now=new Date().toISOString();c.saveOrdersV(c.orders.map(o=>o.id===order.id?{...o,assignedWorker:worker.name,assignedWorkerId:worker.id,updatedAt:now}:o));appendAudit('Assign worker',`${order.invoiceNo} → ${worker.name}`)}return true}catch(e:any){c.flash(e.message||'Assignment gagal');return false}}
  const auto=async()=>{if(!eligible.length)return c.flash('Tidak ada order Baru yang belum ditugaskan');setBusy(true);let count=0;try{let localOrders=[...c.orders];for(const order of eligible){const target=chooseWorkerForOrder(c.workers,localOrders,order);if(!target)continue;if(c.ownerCloud){const ok=await assign(order,target,false);if(ok){count++;localOrders=localOrders.map(o=>o.id===order.id?{...o,assignedWorker:target.name,assignedWorkerId:target.cloudUserId||target.id}:o)}}else{localOrders=localOrders.map(o=>o.id===order.id?{...o,assignedWorker:target.name,assignedWorkerId:target.id,updatedAt:new Date().toISOString()}:o);count++}}if(!c.ownerCloud&&count){c.saveOrdersV(localOrders);appendAudit('Auto Worker Queue',`${count} order dibagikan otomatis`)}if(c.ownerCloud&&count)await c.hydrateCloud();c.flash(`${count} order dibagikan otomatis`)}finally{setBusy(false)}}
  return <div className="space-y-5"><section className="grid gap-3 sm:grid-cols-3"><Metric label="Worker siap" value={String(queue.length)} tone="good"/><Metric label="Order belum ditugaskan" value={String(eligible.length)} tone={eligible.length?'warn':undefined}/><Metric label="Order aktif" value={String(c.orders.filter(o=>o.status==='Baru'||o.status==='Diproses'||o.status==='Menunggu').length)}/></section><Card title="Worker Queue" subtitle="Prioritas assignment: worker aktif yang diizinkan untuk game tersebut dan memiliki antrean aktif paling sedikit." action={<button className="btn-primary" disabled={busy} onClick={()=>void auto()}>{busy?'Membagikan...':'Auto Assign Semua'}</button>}><Table headers={['Worker','Antrean aktif','Selesai hari ini','Game diizinkan','Status']}>{queue.map(x=><tr key={x.worker.id}><Td><strong>{x.worker.name}</strong></Td><Td>{x.activeOrders}</Td><Td>{x.completedToday}</Td><Td>{x.eligibleGames.length?x.eligibleGames.join(', '):'Semua'}</Td><Td><Badge tone="green">Siap</Badge></Td></tr>)}</Table>{!queue.length&&<Empty text="Belum ada Worker aktif dengan izin proses order."/>}</Card><Card title="Order Belum Ditugaskan"><Table headers={['Invoice','Produk','Game','Dibuat','Saran Worker','Aksi']}>{eligible.map(o=>{const target=chooseWorkerForOrder(c.workers,c.orders,o);return <tr key={o.id}><Td><strong>{o.invoiceNo}</strong></Td><Td>{o.productName} × {o.qty}</Td><Td>{o.game}</Td><Td>{fmt(o.createdAt)}</Td><Td>{target?.name||'Tidak ada yang eligible'}</Td><Td>{target?<button className="tiny-btn" onClick={()=>void assign(o,target)}>Assign</button>:'-'}</Td></tr>})}</Table>{!eligible.length&&<Empty text="Semua order Baru sudah ditugaskan."/>}</Card></div>
}

export function ReportGeneratorView(c:V41Ctx){
  const [period,setPeriod]=useState('30');const [startText,setStartText]=useState('');const [endText,setEndText]=useState('')
  const range=useMemo(()=>{const end=endText?new Date(`${endText}T23:59:59`):new Date();const start=startText?new Date(`${startText}T00:00:00`):new Date(end.getTime()-(Number(period)-1)*86400000);return {start,end}},[period,startText,endText])
  const report=useMemo(()=>reportSummary(c.orders,c.expenses,range.start,range.end),[c.orders,c.expenses,range.start.getTime(),range.end.getTime()])
  const download=(kind:'html'|'csv')=>{let content='',type='',ext='';if(kind==='csv'){const lines=['game,orders,revenue,profit',...report.topGames.map(x=>`"${x.game.replace(/"/g,'""')}",${x.orders},${x.revenue},${x.profit}`)];content='\ufeff'+lines.join('\n');type='text/csv;charset=utf-8';ext='csv'}else{content=`<!doctype html><html><head><meta charset="utf-8"><title>Laporan Itemku Profit</title><style>body{font-family:Arial,sans-serif;padding:32px;color:#111}h1{margin-bottom:4px}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin:24px 0}.box{border:1px solid #ddd;border-radius:12px;padding:14px}table{width:100%;border-collapse:collapse}th,td{border-bottom:1px solid #ddd;padding:9px;text-align:left}@media print{button{display:none}}</style></head><body><h1>Itemku Profit V5.2</h1><p>${range.start.toLocaleDateString('id-ID')} – ${range.end.toLocaleDateString('id-ID')}</p><div class="grid"><div class="box"><b>Order selesai</b><br>${report.done.length}</div><div class="box"><b>Omzet</b><br>${money(report.revenue)}</div><div class="box"><b>Profit bersih</b><br>${money(report.netProfit)}</div><div class="box"><b>Profit kotor</b><br>${money(report.grossProfit)}</div><div class="box"><b>Pengeluaran</b><br>${money(report.expenseTotal)}</div><div class="box"><b>Refund/Cancel</b><br>${report.refunds.length}</div></div><h2>Profit per Game</h2><table><thead><tr><th>Game</th><th>Order</th><th>Omzet</th><th>Profit</th></tr></thead><tbody>${report.topGames.map(x=>`<tr><td>${escapeHtml(x.game)}</td><td>${x.orders}</td><td>${money(x.revenue)}</td><td>${money(x.profit)}</td></tr>`).join('')}</tbody></table><p style="margin-top:32px;color:#666">Generated ${new Date().toLocaleString('id-ID')}</p><button onclick="window.print()">Print / Save PDF</button></body></html>`;type='text/html;charset=utf-8';ext='html'}const blob=new Blob([content],{type});const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=`laporan-itemku-${range.start.toISOString().slice(0,10)}-${range.end.toISOString().slice(0,10)}.${ext}`;a.click();URL.revokeObjectURL(u)}
  return <div className="space-y-5"><Card title="Report Generator V5.2" subtitle="Buat laporan periode tertentu. HTML dapat dibuka lalu Print → Save as PDF."><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><label className="grid gap-1.5 text-xs font-semibold">Preset<select className="input h-10" value={period} onChange={e=>{setPeriod(e.target.value);setStartText('');setEndText('')}}><option value="1">Hari ini</option><option value="7">7 hari</option><option value="30">30 hari</option><option value="90">90 hari</option></select></label><Field type="date" label="Mulai (custom)" value={startText} onChange={setStartText}/><Field type="date" label="Sampai (custom)" value={endText} onChange={setEndText}/><div className="flex items-end gap-2"><button className="btn-secondary flex-1" onClick={()=>download('csv')}>CSV</button><button className="btn-primary flex-1" onClick={()=>download('html')}>Laporan</button></div></div></Card><section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-6"><Metric label="Order selesai" value={String(report.done.length)}/><Metric label="Omzet" value={money(report.revenue)}/><Metric label="Profit kotor" value={money(report.grossProfit)} tone="good"/><Metric label="Pengeluaran" value={money(report.expenseTotal)} tone="warn"/><Metric label="Profit bersih" value={money(report.netProfit)} tone={report.netProfit>=0?'good':'bad'}/><Metric label="Refund / Cancel" value={String(report.refunds.length)} tone={report.refunds.length?'warn':undefined}/></section><Card title="Game Teratas"><Table headers={['Game','Order','Omzet','Profit']}>{report.topGames.map(x=><tr key={x.game}><Td><strong>{x.game}</strong></Td><Td>{x.orders}</Td><Td>{money(x.revenue)}</Td><Td className={x.profit>=0?'text-emerald-700':'text-red-600'}>{money(x.profit)}</Td></tr>)}</Table>{!report.topGames.length&&<Empty text="Belum ada transaksi selesai pada periode ini."/>}</Card></div>
}

function escapeHtml(v:string){return v.replace(/[&<>"']/g,ch=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[ch]||ch))}
function Card({title,subtitle,children,action}:{title:string;subtitle?:string;children:React.ReactNode;action?:React.ReactNode}){return <section className="rounded-2xl border bg-card p-5 shadow-sm"><div className="mb-4 flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-base font-bold">{title}</h2>{subtitle&&<p className="mt-1 max-w-3xl text-xs leading-relaxed text-muted-foreground">{subtitle}</p>}</div>{action}</div>{children}</section>}
function Metric({label,value,tone}:{label:string;value:string;tone?:'good'|'bad'|'warn'}){const cls=tone==='good'?'text-emerald-700':tone==='bad'?'text-red-600':tone==='warn'?'text-amber-700':'';return <div className="rounded-xl border bg-card p-4"><span className="block text-xs text-muted-foreground">{label}</span><strong className={`mt-1 block text-xl ${cls}`}>{value}</strong></div>}
function Field({label,value,onChange,type='text'}:{label:string;value:string;onChange:(v:string)=>void;type?:string}){return <label className="grid gap-1.5 text-xs font-semibold">{label}<input type={type} value={value} onChange={e=>onChange(e.target.value)} className="input h-10"/></label>}
function Num({label,value,onChange}:{label:string;value:number;onChange:(v:number)=>void}){return <label className="grid gap-1.5 text-xs font-semibold">{label}<input type="number" min="0" value={value} onChange={e=>onChange(Math.max(0,Number(e.target.value)||0))} className="input h-10"/></label>}
function MiniNumber({label,value,onChange}:{label:string;value:number;onChange:(v:number)=>void}){return <label className="flex items-center gap-2 text-[10px] font-bold text-muted-foreground">{label}<input className="input h-8 w-16" type="number" min="1" value={value} onChange={e=>onChange(Math.max(1,Number(e.target.value)||1))}/></label>}
function Table({headers,children}:{headers:string[];children:React.ReactNode}){return <div className="overflow-x-auto"><table className="w-full min-w-[820px] border-collapse text-left text-xs"><thead><tr>{headers.map(h=><th key={h} className="border-b px-3 py-2.5 font-semibold text-muted-foreground">{h}</th>)}</tr></thead><tbody>{children}</tbody></table></div>}
function Td({children,className=''}:{children:React.ReactNode;className?:string}){return <td className={`border-b px-3 py-3 align-top ${className}`}>{children}</td>}
function Badge({children,tone='gray'}:{children:React.ReactNode;tone?:string}){const cls=tone==='green'?'bg-emerald-100 text-emerald-800 dark:bg-emerald-950 dark:text-emerald-200':tone==='red'?'bg-red-100 text-red-700 dark:bg-red-950 dark:text-red-200':tone==='amber'?'bg-amber-100 text-amber-800 dark:bg-amber-950 dark:text-amber-200':tone==='blue'?'bg-blue-100 text-blue-700 dark:bg-blue-950 dark:text-blue-200':'bg-muted text-muted-foreground';return <span className={`inline-flex rounded-full px-2 py-1 text-[10px] font-bold ${cls}`}>{children}</span>}
function Empty({text}:{text:string}){return <p className="rounded-xl border border-dashed p-6 text-center text-xs text-muted-foreground">{text}</p>}
function Warning({children,tone}:{children:React.ReactNode;tone:'good'|'warn'|'bad'}){const c=tone==='good'?'border-emerald-200 bg-emerald-50 text-emerald-800 dark:bg-emerald-950/30 dark:text-emerald-200':tone==='bad'?'border-red-200 bg-red-50 text-red-700 dark:bg-red-950/30 dark:text-red-200':'border-amber-200 bg-amber-50 text-amber-800 dark:bg-amber-950/30 dark:text-amber-200';return <div className={`mt-4 rounded-xl border p-3 text-xs font-semibold ${c}`}>{children}</div>}
