'use client'

import { useMemo, useState } from 'react'
import { money, type Expense, type Order, type Product, type Restock } from '../../lib/itemku'
import { type ChannelRule, type Dispute, type Settlement, type Supplier } from '../../lib/v4'
import { anomalyMonitor, deadStockRecovery, executiveBrief, feeStressTest, inventoryAging, opportunityMatrix, profitLeakDetector, supplierScorecard } from '../../lib/v43'

export type V43Ctx={products:Product[];orders:Order[];expenses:Expense[];restocks:Restock[];channelRules:ChannelRule[];suppliers:Supplier[];settlements:Settlement[];disputes:Dispute[];setActive:(s:string)=>void}
const pct=(n:number|null)=>n===null?'Baru':`${Number.isFinite(n)?n!.toFixed(1):'0.0'}%`
const num=(n:number)=>new Intl.NumberFormat('id-ID').format(Math.round(n))

function Card({title,subtitle,children,action}:{title:string;subtitle?:string;children:React.ReactNode;action?:React.ReactNode}){return <section className="rounded-2xl border bg-card p-4 shadow-sm md:p-5"><div className="mb-4 flex items-start justify-between gap-3"><div><h2 className="font-black tracking-tight">{title}</h2>{subtitle&&<p className="mt-1 text-xs text-muted-foreground">{subtitle}</p>}</div>{action}</div>{children}</section>}
function Metric({label,value,tone}:{label:string;value:string;tone?:'good'|'warn'|'bad'}){const cls=tone==='good'?'text-emerald-700 dark:text-emerald-300':tone==='warn'?'text-amber-700 dark:text-amber-300':tone==='bad'?'text-red-600 dark:text-red-300':'';return <div className="rounded-2xl border bg-card p-4"><p className="text-xs font-semibold text-muted-foreground">{label}</p><p className={`mt-1 text-xl font-black ${cls}`}>{value}</p></div>}
function Badge({children,tone='gray'}:{children:React.ReactNode;tone?:'green'|'red'|'amber'|'blue'|'gray'}){const cls={green:'bg-emerald-100 text-emerald-800 dark:bg-emerald-950 dark:text-emerald-200',red:'bg-red-100 text-red-700 dark:bg-red-950 dark:text-red-200',amber:'bg-amber-100 text-amber-800 dark:bg-amber-950 dark:text-amber-200',blue:'bg-blue-100 text-blue-800 dark:bg-blue-950 dark:text-blue-200',gray:'bg-muted text-muted-foreground'}[tone];return <span className={`inline-flex rounded-full px-2 py-1 text-[10px] font-black ${cls}`}>{children}</span>}
function Table({headers,children}:{headers:string[];children:React.ReactNode}){return <div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-xs"><thead><tr className="border-b text-muted-foreground">{headers.map(h=><th key={h} className="px-3 py-2 font-bold">{h}</th>)}</tr></thead><tbody>{children}</tbody></table></div>}
function Td({children,className=''}:{children:React.ReactNode;className?:string}){return <td className={`border-b px-3 py-3 align-top ${className}`}>{children}</td>}
function Empty({text}:{text:string}){return <div className="rounded-xl border border-dashed p-8 text-center text-sm text-muted-foreground">{text}</div>}

export function ExecutiveBriefView(c:V43Ctx){const x=useMemo(()=>executiveBrief(c.products,c.orders,c.settlements,c.disputes),[c.products,c.orders,c.settlements,c.disputes]);return <div className="space-y-5"><section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-6"><Metric label="Omzet 7 hari" value={money(x.revenue7)} tone={x.growthRevenue!==null&&x.growthRevenue>=0?'good':'warn'}/><Metric label="Profit 7 hari" value={money(x.profit7)} tone={x.profit7>=0?'good':'bad'}/><Metric label="Order 7 hari" value={String(x.orders7)}/><Metric label="Growth omzet" value={pct(x.growthRevenue)} tone={x.growthRevenue!==null&&x.growthRevenue>=0?'good':'warn'}/><Metric label="Modal tertahan stok" value={money(x.capitalLocked)} tone={x.capitalLocked>0?'warn':undefined}/><Metric label="Refund 30 hari" value={pct(x.refundRate30)} tone={x.refundRate30>=15?'bad':x.refundRate30>=5?'warn':'good'}/></section><Card title="Executive Brief V5.2" subtitle="Ringkasan keputusan Owner berdasarkan penjualan, stok, margin, payout, dan dispute."><div className="grid gap-3 lg:grid-cols-2">{x.actions.map((a,i)=><button key={`${a.title}-${i}`} onClick={()=>c.setActive(a.target)} className="rounded-xl border p-4 text-left transition hover:bg-muted/40"><div className="flex items-center justify-between gap-2"><strong className="text-sm">{a.title}</strong><Badge tone={a.level==='danger'?'red':a.level==='warn'?'amber':'blue'}>{a.level==='danger'?'Prioritas':a.level==='warn'?'Perlu cek':'Info'}</Badge></div><p className="mt-2 text-xs text-muted-foreground">{a.detail}</p><p className="mt-3 text-[10px] font-black text-primary">Buka {a.target} →</p></button>)}</div></Card><section className="grid gap-3 sm:grid-cols-3"><Metric label="Growth profit" value={pct(x.growthProfit)} tone={x.growthProfit!==null&&x.growthProfit>=0?'good':'warn'}/><Metric label="Settlement gap" value={money(x.settlementGap)} tone={x.settlementGap?'warn':'good'}/><Metric label="Dispute terbuka" value={String(x.openDisputes)} tone={x.openDisputes?'warn':'good'}/></section></div>}

export function ProfitLeakView(c:V43Ctx){const rows=useMemo(()=>profitLeakDetector(c.products,c.orders,c.settlements),[c.products,c.orders,c.settlements]);const impact=rows.reduce((s,x)=>s+x.impact,0);return <div className="space-y-5"><section className="grid gap-3 sm:grid-cols-3"><Metric label="Temuan" value={String(rows.length)} tone={rows.length?'warn':'good'}/><Metric label="Kritis" value={String(rows.filter(x=>x.severity==='Kritis').length)} tone={rows.some(x=>x.severity==='Kritis')?'bad':'good'}/><Metric label="Nilai terpapar/tertahan" value={money(impact)} tone={impact?'warn':'good'}/></section><Card title="Profit Leak Detector" subtitle="Mencari kebocoran dari margin, refund, stok menua, dan selisih settlement."><Table headers={['Jenis','Temuan','Detail','Impact','Prioritas','Aksi']}>{rows.map(x=><tr key={x.id}><Td><Badge tone={x.kind==='Margin'?'red':x.kind==='Refund'?'amber':x.kind==='Settlement'?'blue':'gray'}>{x.kind}</Badge></Td><Td><strong>{x.title}</strong></Td><Td>{x.detail}</Td><Td>{money(x.impact)}</Td><Td><Badge tone={x.severity==='Kritis'?'red':'amber'}>{x.severity}</Badge></Td><Td><button className="rounded-lg border px-2 py-1 font-bold" onClick={()=>c.setActive(x.target)}>Periksa</button></Td></tr>)}</Table>{!rows.length&&<Empty text="Tidak ada kebocoran profit yang terdeteksi."/>}</Card></div>}

export function InventoryAgingView(c:V43Ctx){const rows=useMemo(()=>inventoryAging(c.products,c.orders),[c.products,c.orders]);const buckets=['0–7 hari','8–14 hari','15–30 hari','>30 hari'] as const;return <div className="space-y-5"><section className="grid gap-3 sm:grid-cols-4">{buckets.map((b,i)=>{const r=rows.filter(x=>x.bucket===b),capital=r.reduce((s,x)=>s+x.capitalLocked,0);return <Metric key={b} label={b} value={`${r.length} SKU · ${money(capital)}`} tone={i>=2&&capital>0?i===3?'bad':'warn':undefined}/>})}</section><Card title="Inventory Aging Heatmap" subtitle="Menunjukkan umur stok dan modal yang masih tertahan per SKU."><Table headers={['Produk','Umur stok','Stok','Terjual 30h','Turnover','Modal tertahan','Bucket']}>{rows.map(x=><tr key={x.productId}><Td><strong>{x.productName}</strong><small className="block text-muted-foreground">{x.game}</small></Td><Td>{Math.floor(x.ageDays)} hari</Td><Td>{x.stock}</Td><Td>{x.sold30}</Td><Td>{pct(x.turnover)}</Td><Td>{money(x.capitalLocked)}</Td><Td><Badge tone={x.bucket==='>30 hari'?'red':x.bucket==='15–30 hari'?'amber':x.bucket==='8–14 hari'?'blue':'green'}>{x.bucket}</Badge></Td></tr>)}</Table>{!rows.length&&<Empty text="Tidak ada stok aktif untuk dianalisis."/>}</Card></div>}

export function SupplierScorecardView(c:V43Ctx){const rows=useMemo(()=>supplierScorecard(c.suppliers,c.restocks,c.products,c.orders),[c.suppliers,c.restocks,c.products,c.orders]);return <Card title="Supplier Scorecard" subtitle="Skor berdasarkan margin transaksi, refund, volume order, cakupan produk, dan histori restock."><Table headers={['Supplier','Score','Produk','Restock','Belanja stok','Avg cost','Order 30h','Profit 30h','Refund']}>{rows.map(x=><tr key={x.supplier}><Td><strong>{x.supplier}</strong></Td><Td><Badge tone={x.label==='Unggul'?'green':x.label==='Baik'?'blue':x.label==='Pantau'?'amber':'red'}>{x.score} · {x.label}</Badge></Td><Td>{x.products}</Td><Td>{x.restockCount}</Td><Td>{money(x.spend)}</Td><Td>{money(x.avgUnitCost)}</Td><Td>{x.orders30}</Td><Td className={x.profit30>=0?'text-emerald-700':'text-red-600'}>{money(x.profit30)}</Td><Td>{pct(x.refundRate)}</Td></tr>)}</Table>{!rows.length&&<Empty text="Belum ada data supplier/restock yang cukup."/>}</Card>}

export function FeeStressView(c:V43Ctx){const channels=[...new Set(['Itemku','WhatsApp','Direct',...c.channelRules.filter(x=>x.active).map(x=>x.name)])];const [channel,setChannel]=useState(channels[0]||'Itemku');const [extra,setExtra]=useState(2);const rows=useMemo(()=>feeStressTest(c.products,c.channelRules,channel,extra),[c.products,c.channelRules,channel,extra]);return <div className="space-y-5"><Card title="Fee Stress Test" subtitle="Simulasikan kenaikan fee marketplace untuk melihat SKU yang akan menjadi margin tipis atau rugi."><div className="grid gap-3 sm:grid-cols-2"><label className="grid gap-1 text-xs font-bold">Channel<select className="input h-10" value={channel} onChange={(e:any)=>setChannel(e.target.value)}>{channels.map(x=><option key={x}>{x}</option>)}</select></label><label className="grid gap-1 text-xs font-bold">Tambahan fee (%)<input className="input h-10" type="number" min="0" max="30" step="0.5" value={extra} onChange={(e:any)=>setExtra(Math.max(0,Number(e.target.value)||0))}/></label></div></Card><section className="grid gap-3 sm:grid-cols-3"><Metric label="Aman" value={String(rows.filter(x=>x.status==='Aman').length)} tone="good"/><Metric label="Margin tipis" value={String(rows.filter(x=>x.status==='Tipis').length)} tone="warn"/><Metric label="Rugi" value={String(rows.filter(x=>x.status==='Rugi').length)} tone={rows.some(x=>x.status==='Rugi')?'bad':'good'}/></section><Card title="Dampak per produk"><Table headers={['Produk','Margin sekarang','Margin setelah fee','Profit/unit','Status']}>{rows.map(x=><tr key={x.productId}><Td><strong>{x.productName}</strong><small className="block text-muted-foreground">{x.game}</small></Td><Td>{pct(x.currentMargin)}</Td><Td>{pct(x.stressMargin)}</Td><Td>{money(x.profitPerUnit)}</Td><Td><Badge tone={x.status==='Aman'?'green':x.status==='Tipis'?'amber':'red'}>{x.status}</Badge></Td></tr>)}</Table></Card></div>}

export function DeadStockRecoveryView(c:V43Ctx){const rows=useMemo(()=>deadStockRecovery(c.products,c.orders),[c.products,c.orders]);const shown=rows.filter(x=>x.severity!=='Aman');return <div className="space-y-5"><section className="grid gap-3 sm:grid-cols-3"><Metric label="Perlu tindakan" value={String(shown.length)} tone={shown.length?'warn':'good'}/><Metric label="Modal tertahan" value={money(shown.reduce((s,x)=>s+x.capitalLocked,0))} tone={shown.length?'warn':'good'}/><Metric label="Stok >30 hari" value={String(rows.filter(x=>x.ageDays>30).length)} tone={rows.some(x=>x.ageDays>30)?'bad':'good'}/></section><Card title="Dead Stock Recovery" subtitle="Saran diskon tetap dijaga di atas BEP + buffer 3%, sehingga tidak asal banting harga."><Table headers={['Produk','Umur','Stok','Terjual 30h','Modal tertahan','Harga sekarang','Harga recovery','Status']}>{shown.map(x=><tr key={x.productId}><Td><strong>{x.productName}</strong><small className="block text-muted-foreground">{x.game}</small></Td><Td>{Math.floor(x.ageDays)} hari</Td><Td>{x.stock}</Td><Td>{x.sold30}</Td><Td>{money(x.capitalLocked)}</Td><Td>{money(x.currentPrice)}</Td><Td><strong>{money(x.recommendedPrice)}</strong><small className="block text-muted-foreground">BEP {money(x.bep)}</small></Td><Td><Badge tone={x.severity==='Kritis'?'red':x.severity==='Lambat'?'amber':'blue'}>{x.severity}</Badge></Td></tr>)}</Table>{!shown.length&&<Empty text="Tidak ada dead stock yang membutuhkan recovery."/>}</Card></div>}

export function AnomalyMonitorView(c:V43Ctx){const rows=useMemo(()=>anomalyMonitor(c.products,c.orders,c.expenses),[c.products,c.orders,c.expenses]);return <Card title="Anomaly Monitor" subtitle="Mendeteksi penurunan penjualan, lonjakan refund/pengeluaran, dan margin negatif."><div className="grid gap-3 md:grid-cols-2">{rows.map(x=><button key={x.id} onClick={()=>c.setActive(x.target)} className="rounded-xl border p-4 text-left hover:bg-muted/40"><div className="flex items-center justify-between gap-2"><strong className="text-sm">{x.title}</strong><Badge tone={x.level==='danger'?'red':x.level==='warn'?'amber':'green'}>{x.type}</Badge></div><p className="mt-2 text-xs text-muted-foreground">{x.detail}</p><p className="mt-3 text-[10px] font-black text-primary">Buka {x.target} →</p></button>)}</div></Card>}

export function OpportunityMatrixView(c:V43Ctx){const [filter,setFilter]=useState('Semua');const rows=useMemo(()=>opportunityMatrix(c.products,c.orders),[c.products,c.orders]);const shown=filter==='Semua'?rows:rows.filter(x=>x.quadrant===filter);return <div className="space-y-5"><section className="grid gap-3 sm:grid-cols-4">{(['Scale Up','Jaga','Perbaiki Margin','Kurangi'] as const).map(x=><Metric key={x} label={x} value={String(rows.filter(r=>r.quadrant===x).length)} tone={x==='Scale Up'?'good':x==='Perbaiki Margin'||x==='Kurangi'?'warn':undefined}/>)}</section><Card title="Opportunity Matrix" subtitle="Menggabungkan Product Score, Sales Trend, margin, dan kebutuhan restock menjadi keputusan sederhana." action={<select className="input h-9" value={filter} onChange={(e:any)=>setFilter(e.target.value)}><option>Semua</option><option>Scale Up</option><option>Jaga</option><option>Perbaiki Margin</option><option>Kurangi</option></select>}><Table headers={['Produk','Score','Trend','Restock','Keputusan','Alasan']}>{shown.map(x=><tr key={x.productId}><Td><strong>{x.productName}</strong><small className="block text-muted-foreground">{x.game}</small></Td><Td>{x.performance}/100</Td><Td><Badge tone={x.trend==='Naik'||x.trend==='Baru'?'green':x.trend==='Turun'?'red':'gray'}>{x.trend}</Badge></Td><Td>{x.recommendedRestock?`${num(x.recommendedRestock)} unit · ${x.urgency}`:'-'}</Td><Td><Badge tone={x.quadrant==='Scale Up'?'green':x.quadrant==='Jaga'?'blue':x.quadrant==='Perbaiki Margin'?'amber':'red'}>{x.quadrant}</Badge></Td><Td>{x.reason}</Td></tr>)}</Table>{!shown.length&&<Empty text="Tidak ada produk pada kategori ini."/>}</Card></div>}
